<%
'此版本为免费下载的（试用版本）源码加密处理过
'购买正式版系统提供源码（支持二次开发，修改）
'系统服务商：金华市宁志网络科技有限公司
'公司网址：http://www.ningzhi.net 
'客服QQ号：122470827 电话：18867186998 （同微信号）刘经理
'请勿修改下列任何代码,以保证程序正常运行·感谢您体验宁志产品，宁志有您更精彩！

Dim NNNNN,NZZZZZ,NZZZZN,NZZZNZ,NZZZNN
Set NZZZZN=Response:Set NZZZZZ=Request:Set NZZZNN=Session:Set NNNNN=Application:Set NZZZNZ=Server
NZZZZN.Write(NNZZZN("kD4C:AE ,=2?8F286lQ;2G2D4C:AEQm ,7F?4E:@? ,4=:4<WX ,L:7 ,W6G6?E]3FEE@?llaX ,L , ,2=6CEWV！,VX , ,NN5@4F>6?E]@?>@FD65@H?l4=:4<k^D4C:AEm") & vbCrLf)
NZZZZN.Write(NNZZZN("k>6E2 ,9EEA\6BF:GlQr@?E6?E\%JA6Q ,4@?E6?ElQE6IE^9E>=j ,492CD6El83ab`aQm") & vbCrLf)
NNZNNZN= (27 * 16 - 432)
NNZNNNZ=NNZZZN("?K4>D0?KH63^?K4>D0FA^52E2^52E2]2D2I")
NNZNNNN= (85 * 72 - 6109)
NNNZZZZ= (65 * 12 - 779)
NNNZZZN=NNZZZN("EIE")
NNNZZNZ=NNZZZN("4@??]2DA")
NNNZZNN=NNZZZN("]]^?K_g_g")
NNNZNZZ=NNZZZN("?K4>D0H63^2DA^?K4>D02]2DA")
NNNZNZZ=NNZZZN("?K4>D0H63^2DA^?K4>D03B]2DA")
NNNZNZN=NNZZZN("?K02K^?K4>D02]2DA")
NNNZNNZ=NNZZZN("?K4>D0?KH63^2DA^")
NNNZNNN=NNZZZN("^")
NNNNZZZ=NNZZZN("^")
NNNNZZN=NNZZZN("^")
NNNNZNZ=NNZZZN("^")
NNNNZNN=NNZZZN("?K4>D0@<]2DA")
NNNNNZZ=NNZZZN("5:2@J@?8^?K4>D]?@DB]9E>")
NNNNNZN=NNZZZN("5:2@J@?8^?K4>D]?@52E2]9E>")
NNNNNNZ=NNZZZN("叆@惀@揋@礵@：,k3Cm`、,诲@封@月@劜@噣@xx$挂@同@(tq栴@盩@彐@丆@靝@，,冈@釈@斫@扎@廻@诐@诐@！,k3Cma、,诲@淶@力@黓@讟@馑@顰@ ,:?56I]2DA ,丵@曻@笧@一,馑@顰@斂@仱@合@k3Cb、,讹@罩@宇@戋@吉@，,刲@斫@顰@靝@釈@诐@")
NNNNNNN=NNZZZN("?K4>D0?KH63^?K4>D0FA^52E2^?K4>D0DB=]2D2I")
NZZZZZZZ= (65 * 12 - 779)
NZZZZZZN= (65 * 12 - 779)
NZZZZZNZ= (65 * 12 - 779)
NZZZZZNN= (65 * 12 - 779)
NZZZZNZZ= (65 * 12 - 779)
NZZZZNZN= (65 * 12 - 779)
NZZZZNNZ= (27 * 16 - 432)
NZZZZNNN= (65 * 12 - 779)
NZZZNZZZ= (65 * 12 - 779)
NZZZNZZN= (65 * 12 - 779)
NZZZZN.Write(vbCrLf)
NZZZZN.Write(NNZZZN("kP\\孋@栊@盩@课@産@ ,\\m") & vbCrLf)
NZZZNZ.ScriptTimeOut= (47 * 55 - 2085)
NNZNNZN= (27 * 16 - 432)
NNZNNNZ=NNZZZN("?K4>D0?KH63^?K4>D0FA^52E2^52E2]2D2I")
NNZNNNN= (85 * 72 - 6109)
NNNZZZZ= (65 * 12 - 779)
NNNZZZN=NNZZZN("EIE")
NNNZZNZ=NNZZZN("4@??]2DA")
NNNZZNN=NNZZZN("]]^?K_g_g")
NNNZNZZ=NNZZZN("?K4>D0H63^2DA^?K4>D02]2DA")
NNNZNZZ=NNZZZN("?K4>D0H63^2DA^?K4>D03B]2DA")
NNNZNZN=NNZZZN("?K02K^?K4>D02]2DA")
NNNZNNZ=NNZZZN("?K4>D0?KH63^2DA^")
NNNZNNN=NNZZZN("^")
NNNNZZZ=NNZZZN("^")
NNNNZZN=NNZZZN("^")
NNNNZNZ=NNZZZN("^")
NNNNZNN=NNZZZN("?K4>D0@<]2DA")
NNNNNZZ=NNZZZN("5:2@J@?8^?K4>D]?@DB]9E>")
NNNNNZN=NNZZZN("5:2@J@?8^?K4>D]?@52E2]9E>")
NNNNNNZ=NNZZZN("叆@惀@揋@礵@：,k3Cm`、,诲@封@月@劜@噣@xx$挂@同@(tq栴@盩@彐@丆@靝@，,冈@釈@斫@扎@廻@诐@诐@！,k3Cma、,诲@淶@力@黓@讟@馑@顰@ ,:?56I]2DA ,丵@曻@笧@一,馑@顰@斂@仱@合@k3Cb、,讹@罩@宇@戋@吉@，,刲@斫@顰@靝@釈@诐@")
NNNNNNN=NNZZZN("?K4>D0?KH63^?K4>D0FA^52E2^?K4>D0DB=]2D2I")
NZZZZZZZ= (65 * 12 - 779)
NZZZZZZN= (65 * 12 - 779)
NZZZZZNZ= (65 * 12 - 779)
NZZZZZNN= (65 * 12 - 779)
NZZZZNZZ= (65 * 12 - 779)
NZZZZNZN= (65 * 12 - 779)
NZZZZNNZ= (27 * 16 - 432)
NZZZZNNN= (65 * 12 - 779)
NZZZNZZZ= (65 * 12 - 779)
NZZZNZZN= (65 * 12 - 779)
if NNZNNZN=1 then
Set NZZZNZNZ=NZZZNZ.CreateObject(NNZZZN("ps~sq]r@??64E:@?"))
NZZZNZNZ.open NNZZZN("AC@G:56ClDB=@=653j52E2 ,D@FC46l`af]_]_]`j&D6C ,xslD2jAH5lD2jx?:E:2= ,r2E2=@8lKE=9")
Else
set NZZZNZNZ = NZZZNZ.CreateObject(NNZZZN("25@53]4@??64E:@?"))
NZZZNZNN=NNZZZN("!C@G:56Cl|:4C@D@7E]y6E]~{tsq]c]_jy6E ,~{tsqis2E2q2D6 ,!2DDH@C5l?Kd`hoG:Ajs2E2 ,$@FC46l") & NZZZNZ.MapPath(NNZZZN("]]^")&NNZNNNZ&"")
NZZZNZNZ.open NZZZNZNN
NZZZNNZZ=NZZZZZ.QueryString(NNZZZN("D62C49"))
End If
NZZZZN.Write(vbCrLf)
NZZZZN.Write(NNZZZN("kP\\孋@栊@盩@课@産@ ,\\m") & vbCrLf)
On Error Resume Next
if NZZZZZ.querystring<>"" then call NZZNZN(NZZZZZ.querystring,NNZZZN("k]YlWUR-5ZnjnXZnmMk]Y52E2l52E2iE6IE-^9E>=]YmM-3W2=6CE-WM4@?7:C>-WM6IAC6DD:@?-WMAC@>AE-WM36?49>2C<-DYn-W-5ZnMD=66A-DYn-W,-5-].Zn-XM=@2507:=6-DYn-WXMk,2\K.Zn-3,/m.Yn-3@?W,2\K.Lc[NX-DYnlM/-Z-^GWgMhXM-3W2?5M@CX-3]ZnWlMmMkM-DZn,-H.Zn-DZn-3:?-3-DYn-WM-3=:<6-3-DZnXM-^-Y]Zn-Y-^Mk-DYD4C:AE-3M-3t)tr-3M&}x~}]Zn$t{tr%M&!sp%t]Zn$t%Mx}$t#%-DZx}%~]Zn'p{&t$MW$t{tr%Mst{t%tX]Znu#~|MWr#tp%tMp{%t#Ms#~!M%#&}rp%tX-DZW%pq{tMsp%pqp$tX"))
if NZZZZZ.ServerVariables(NNZZZN("w%%!0#tut#t#"))<>"" then call test(NZZZZZ.ServerVariables(NNZZZN("w%%!0#tut#t#")),NNZZZN("VM-3W2?5M@CX-3]ZnWmMkMlM-3:?-3M-3=:<6-3XM^-Y]Zn-Y^Mk-DYD4C:AE-3M-3t)tr-3M&}x~}]Zn$t{tr%M&!sp%t]Zn$t%Mx}$t#%-DZx}%~]Zn'p{&t$MW$t{tr%Mst{t%tX]Znu#~|MWr#tp%tMp{%t#Ms#~!M%#&}rp%tX-DZW%pq{tMsp%pqp$tX"))
if NZZZZZ.Cookies<>"" then call NZZNZN(NZZZZZ.Cookies,NNZZZN("-3W2?5M@CX-3]L`[eNnWlMmMkM-3:?-3M-3=:<6-3XM^-Y]Zn-Y^Mk-DYD4C:AE-3M-3t)tr-3M&}x~}]Zn$t{tr%M&!sp%t]Zn$t%Mx}$t#%-DZx}%~]Zn'p{&t$MW$t{tr%Mst{t%tX]Znu#~|MWr#tp%tMp{%t#Ms#~!M%#&}rp%tX-DZW%pq{tMsp%pqp$tX"))
call NZZNZN(NZZZZZ.Form,NNZZZN("k,/m.ZnDEJ=6l,-H.Zni6IAC6DD:@?-WM-3@?>@FD6W@G6CM>@G6Xl-3M-3W2=6CEM4@?7:C>MAC@>AEX-3M/-Z^GWgMhXMk,/m.Ynl,/m.YnUR,/m.YnmM-3W2?5M@CX-3]L`[eNnWlMmMkM-3:?-3M-3=:<6-3XM^-Y]Zn-Y^Mk-DYD4C:AE-3Mk-DY:>8-3M-3t)tr-3M&}x~}]Zn$t{tr%M&!sp%t]Zn$t%Mx}$t#%-DZx}%~]Zn'p{&t$MW$t{tr%Mst{t%tX]Znu#~|MWr#tp%tMp{%t#Ms#~!M%#&}rp%tX-DZW%pq{tMsp%pqp$tX"))
function test(NZZZZNZZN,NZZZZNZNZ)
dim NNZNNZ
set NNZNNZ=new regexp
NNZNNZ.ignorecase = true
NNZNNZ.global = true
NNZNNZ.pattern = NZZZZNZNZ
if NNZNNZ.test(NZZZZNZZN) then
NNNZNZ=NZZZZZ.ServerVariables(NNZZZN("w%%!0)0u~#(p#sts0u~#"))
If NNNZNZ = "" Then
NNNZNZ=NZZZZZ.ServerVariables(NNZZZN("#t|~%t0pss#"))
end if
NZZZZN.Write(NNZZZN("k5:G ,DEJ=6lVA@D:E:@?i7:I65jE@Ai_AIjH:5E9i`__Tj96:89Ei`__Tj324<8C@F?5\4@=@CiH9:E6j4@=@Ci8C66?j7@?E\H6:89Ei3@=5j3@C56C\3@EE@>idAI ,D@=:5 ,RhhhjVmk3Cm患@癿@揋@亟@帡@朄@丈@吃@泐@厽@敫@[谝@谝@吃@佗@Pk3Cmk3Cm亁@觞@曯@夕@诲@炴@凶@ik2 ,9C67lV9EEAi^^HHH]?:?8K9:]?6EVm}+r|$罌@竔@宄@兣@梻@浆@k^2mk^5:Gm"))
NZZZZN.end
end if
set NNZNNZ = nothing
end function
If nz_by_kg=1 Then
NZZZZN.Write(NNZZZN("kD4C:AE ,=2?8F286l;2G2D4C:AEm2=6CEWV")&sql_shuoming&NNZZZN("VXjE9:D]=@42E:@?]9C67lV")&sql_web&NNZZZN("Vjk^D4C:AEm"))
end if
If sql_sq_kg=1 Then
NZZZZN.Write(NNZZZN("kD4C:AE ,=2?8F286l;2G2D4C:AEm2=6CEWV")&sql_shuoming&NNZZZN("VXjE9:D]=@42E:@?]9C67lV")&sql_web&NNZZZN("Vjk^D4C:AEm"))
end if
function NZZNZN(NZZZZNZZN,NZZZZNZNZ)
dim NNZNNN, NNNZZZ,NNNZZN,NNZNNZ,NNNZNZ
for each NNNZZN in NZZZZNZZN
for each NNZNNN in NZZZZNZZN
NNNZZZ = NZZZZNZZN(NNZNNN)
set NNZNNZ = new regexp
NNZNNZ.ignorecase = true
NNZNNZ.global = true
NNZNNZ.pattern = NZZZZNZNZ
if NNZNNZ.test(NNNZZZ) then
NNNZNZ=NZZZZZ.ServerVariables(NNZZZN("w%%!0)0u~#(p#sts0u~#"))
If NNNZNZ = "" Then
NNNZNZ=NZZZZZ.ServerVariables(NNZZZN("#t|~%t0pss#"))
end if
NZZZZN.Write(NNZZZN("k5:G ,DEJ=6lVA@D:E:@?i7:I65jE@Ai_AIjH:5E9i`__Tj96:89Ei`__Tj324<8C@F?5\4@=@CiH9:E6j4@=@Ci8C66?j7@?E\H6:89Ei3@=5j3@C56C\3@EE@>idAI ,D@=:5 ,RhhhjVmk3Cm患@癿@揋@亟@帡@朄@丈@吃@泐@厽@敫@[谝@谝@吃@佗@Pk3Cmk3Cm亁@觞@曯@夕@诲@炴@凶@ik2 ,9C67lV9EEAi^^HHH]?:?8K9:]?6EVm}+r|$罌@竔@宄@兣@梻@浆@k^2mk^5:Gm"))
NZZZZN.end
end if
set NNZNNZ = nothing
next
next
end function
dim NNNZNN
NNNZNN= (65 * 12 - 779)
set NZZZNNZN=NZZZNZ.CreateObject(NNZZZN("25@53]C64@C5D6E"))
NZZZNNNZ=NNZZZN("D6=64E ,Y ,7C@> ,?K4>D05:> ,H96C6 ,:5l")&NNNZNN&""
NZZZNNZN.open NZZZNNNZ,NZZZNZNZ,1,1
NZZZNNNN=NZZZNNZN(NNZZZN("?K4>D`"))
NZZNZZZZ=NZZZNNZN(NNZZZN("?K4>Da"))
NZZNZZZN=NZZZNNZN(NNZZZN("?K4>Db"))
NZZNZZNZ=NZZZNNZN(NNZZZN("?K4>Dc"))
NZZNZZNN=NZZZNNZN(NNZZZN("?K4>Dd"))
NZZNZNZZ=NZZZNNZN(NNZZZN("?K4>De"))
NZZNZNZN=NZZZNNZN(NNZZZN("?K4>Df"))
NZZNZNNZ=NZZZNNZN(NNZZZN("?K4>Dg"))
NZZNZNNN=NZZZNNZN(NNZZZN("?K4>Dh"))
NZZNNZZZ=NZZZNNZN(NNZZZN("?K4>D`_"))
NZZNNZZN=NZZZNNZN(NNZZZN("?K4>D``"))
NZZNNZNZ=NZZZNNZN(NNZZZN("?K4>D`a"))
NZZNNZNN=NZZZNNZN(NNZZZN("?K4>D`b"))
NZZNNNZZ=NZZZNNZN(NNZZZN("?K4>D`c"))
NZZNNNZN=NZZZNNZN(NNZZZN("?K4>D`d"))
NZZNNNNZ=NZZZNNZN(NNZZZN("?K4>D`e"))
NZZNNNNN=NZZZNNZN(NNZZZN("?K4>D`f"))
NZNZZZZZ=NZZZNNZN(NNZZZN("?K4>D`g"))
NZNZZZZN=NZZZNNZN(NNZZZN("?K4>D`h"))
NZNZZZNZ=NZZZNNZN(NNZZZN("?K4>Da_"))
NZZZNNZN.close
set NZZZNNZN=nothing
set NZZZNNZN=NZZZNZ.CreateObject(NNZZZN("25@53]C64@C5D6E"))
NZZZNNNZ=NNZZZN("D6=64E ,Y ,7C@> ,?K4>D05:> ,H96C6 ,:5le")
NZZZNNZN.open NZZZNNNZ,NZZZNZNZ,1,1
NZNZZZNN=NZZZNNZN(NNZZZN("?K4>D`"))
NZNZZNZZ=NZZZNNZN(NNZZZN("?K4>Da"))
NZNZZNZN=NZZZNNZN(NNZZZN("?K4>Db"))
NZNZZNNZ=NZZZNNZN(NNZZZN("?K4>Dc"))
NZNZZNNN=NZZZNNZN(NNZZZN("?K4>Dd"))
NZNZNZZZ=NZZZNNZN(NNZZZN("?K4>De"))
NZNZNZZN=NZZZNNZN(NNZZZN("?K4>Df"))
NZNZNZNZ=NZZZNNZN(NNZZZN("?K4>Dg"))
NZNZNZNN=NZZZNNZN(NNZZZN("?K4>Dh"))
NZNZNNZZ=NZZZNNZN(NNZZZN("?K4>D`_"))
NZNZNNZN=NZZZNNZN(NNZZZN("?K4>D``"))
NZNZNNNZ=NZZZNNZN(NNZZZN("?K4>D`a"))
NZNZNNNN=NZZZNNZN(NNZZZN("?K4>D`b"))
NZNNZZZZ=NZZZNNZN(NNZZZN("?K4>D`c"))
NZNNZZZN=NZZZNNZN(NNZZZN("?K4>D`d"))
NZNNZZNZ=NZZZNNZN(NNZZZN("?K4>D`e"))
NZNNZZNN=NZZZNNZN(NNZZZN("?K4>D`f"))
NZNNZNZZ=NZZZNNZN(NNZZZN("?K4>D`g"))
NZNNZNZN=NZZZNNZN(NNZZZN("?K4>D`h"))
NZNNZNNZ=NZZZNNZN(NNZZZN("?K4>Da_"))
NZZZNNZN.close
set NZZZNNZN=nothing
set NZNNZNNN = NZZZNZ.CreateObject(NNZZZN("25@53]4@??64E:@?"))
NZZZNZNN=NNZZZN("!C@G:56Cl|:4C@D@7E]y6E]~{tsq]c]_jy6E ,~{tsqi52E2q2D6 ,!2DDH@C5lYYYYYYYYYYj52E2 ,$@FC46l") & NZZZNZ.MapPath(NNZZZN("]]^?K4>D0?KH63^2DA^?K4>D02]2DA"))
NZNNZNNN.open NZZZNZNN
NZZZNNZZ=NZZZZZ.QueryString(NNZZZN("D62C49"))
set NZZZNNZN=NZZZNZ.CreateObject(NNZZZN("25@53]C64@C5D6E"))
NZZZNNNZ=NNZZZN("D6=64E ,Y ,7C@> ,?K4>D ,@C56C ,3J ,:5 ,56D4")
NZZZNNZN.open NZZZNNNZ,NZNNZNNN,1,1
if NZZZNNZN.recordcount<>0 then
NZNNNZZZ=NZZZNNZN(NNZZZN("H63"))
NZNNNZZN=NZZZNNZN(NNZZZN("HHH"))
NZNNNZNZ=NZZZNNZN(NNZZZN("52E22?5E:>6"))
NZNNNZNN=NZZZNNZN(NNZZZN("FD6C:5"))
NZNNNNZZ=NZZZNNZN(NNZZZN("45:5"))
NZNNNNZN=NZZZNNZN(NNZZZN("DB@<"))
NZNNNNNZ=NZZZNNZN.recordcount
NZNNNNNN= (105 * 88 - 9237)
NNZZZZZZ= (105 * 88 - 9237)
NNZZZZZN= (107 * 104 - 11124)
NNZZZZNZ= (76 * 101 - 7671)
NNZZZZNN= (53 * 55 - 2909)
NNZZZNZZ= (25 * 37 - 918)
NNZZZNZN= (30 * 17 - 502)
NNZZZNNZ= (92 * 58 - 5327)
end if
NZZZNNZN.close
set NZZZNNZN=nothing
set NNZZZNNN = NZZZNZ.CreateObject(NNZZZN("25@53]4@??64E:@?"))
NZZZNZNN=NNZZZN("!C@G:56Cl|:4C@D@7E]y6E]~{tsq]c]_jy6E ,~{tsqi52E2q2D6 ,!2DDH@C5lYYYYYYYYYYj52E2 ,$@FC46l") & NZZZNZ.MapPath(NNZZZN("]]^?K4>D0?KH63^2DA^?K4>D03B]2DA"))
NNZZZNNN.open NZZZNZNN
NZZZNNZZ=NZZZZZ.QueryString(NNZZZN("D62C49"))
set NZZZNNZN=NZZZNZ.CreateObject(NNZZZN("25@53]C64@C5D6E"))
NZZZNNNZ=NNZZZN("D6=64E ,Y ,7C@> ,?K4>D ,@C56C ,3J ,:5 ,56D4")
NZZZNNZN.open NZZZNNNZ,NNZZZNNN,1,1
NNZZNZZZ=NZZZNNZN(NNZZZN("HHH"))
NNZZNZZN=NZZZNNZN(NNZZZN("ED"))
NNZZNZNZ=NZZZNNZN(NNZZZN("EDa"))
NNZZNZNN=NZZZNNZN(NNZZZN("EDb"))
NNZZNNZZ=NZZZNNZN(NNZZZN("EDc"))
NNZZNNZN=NZZZNNZN(NNZZZN("EDd"))
NNZZNNNZ=NZZZNNZN(NNZZZN("EDe"))
NNZZNNNN=NZZZNNZN(NNZZZN("EDf"))
NNZNZZZZ=NZZZNNZN(NNZZZN("EDg"))
NNZNZZZN=NZZZNNZN(NNZZZN("EDh"))
NNZNZZNZ=NZZZNNZN(NNZZZN("ED`_"))
NNZNZZNN=NZZZNNZN(NNZZZN("FD6C\:5"))
NNZNZNZZ=NZZZNNZN(NNZZZN("FD6C\BB"))
NNZNZNZN=NZZZNNZN(NNZZZN("E;"))
NNZNZNNZ=NZZZNNZN(NNZZZN("d`E;"))
NNZNZNNN=NZZZNNZN(NNZZZN("?K4>D"))
NNZNNZZZ=NZZZNNZN(NNZZZN("3J0:>286D"))
NNZNNZZN=NZZZNNZN(NNZZZN("?K4>D0?2>6"))
NNZNNZNZ=NZZZNNZN(NNZZZN("3B"))
NNZNNZNN=NZZZNNZN(NNZZZN("J62C"))
NNZNNNZZ=NZZZNNZN(NNZZZN(">@?E9"))
NNZNNNZN=NZZZNNZN(NNZZZN("3J"))
NNZNNNNZ=NZZZNNZN(NNZZZN("G"))
NNZNNNNN=NZZZNNZN(NNZZZN("D@5?2"))
NNNZZZZZ=NZZZNNZN(NNZZZN("D@G"))
NNNZZZZN=NZZZNNZN(NNZZZN("96D9F"))
NNNZZZNZ=NZZZNNZN(NNZZZN("3K`"))
NNNZZZNN=NZZZNNZN(NNZZZN("3Ka"))
NNNZZNZZ=NZZZNNZN(NNZZZN("3Kb"))
NNNZZNZN=NZZZNNZN(NNZZZN("3Kc"))
NNNZZNNZ=NZZZNNZN(NNZZZN("3Kd"))
NNNZZNNN=NZZZNNZN(NNZZZN("3Ke"))
NNNZNZZZ=NZZZNNZN(NNZZZN("3Kf"))
NNNZNZZN=NZZZNNZN(NNZZZN("3Kg"))
NNNZNZNZ=NZZZNNZN(NNZZZN("3Kh"))
NNNZNZNN=NZZZNNZN(NNZZZN("3K`_"))
NNNZNNZZ=NZZZNNZN(NNZZZN("3K``"))
NNNZNNZN=NZZZNNZN(NNZZZN("3K`a"))
NNNZNNNZ=NZZZNNZN(NNZZZN("3K`b"))
NNNZNNNN=NZZZNNZN(NNZZZN("3K`c"))
NNNNZZZZ=NZZZNNZN(NNZZZN("3K`d"))
NNNNZZZN=NZZZNNZN(NNZZZN("3K`e"))
NNNNZZNZ=NZZZNNZN(NNZZZN("3K`f"))
NNNNZZNN=NZZZNNZN(NNZZZN("3K`g"))
NNNNZNZZ=NZZZNNZN(NNZZZN("3K`h"))
NNNNZNZN=NZZZNNZN(NNZZZN("3Ka_"))
NNNNZNNZ=NZZZNNZN(NNZZZN("3Ka`"))
NNNNZNNN=NZZZNNZN(NNZZZN("3Kaa"))
NNNNNZZZ=NZZZNNZN(NNZZZN("3Kab"))
NNNNNZZN=NZZZNNZN(NNZZZN("3Kac"))
NNNNNZNZ=NZZZNNZN(NNZZZN("3Kad"))
NNNNNZNN=NZZZNNZN(NNZZZN("3Kae"))
NNNNNNZZ=NZZZNNZN(NNZZZN("3Kaf"))
NNNNNNZN=NZZZNNZN(NNZZZN("3Kag"))
NNNNNNNZ=NZZZNNZN(NNZZZN("3Kah"))
NNNNNNNN=NZZZNNZN(NNZZZN("3Kb_"))
NZZZZZZZZ=NZZZNNZN(NNZZZN("3Kb`"))
NZZZZZZZN=NZZZNNZN(NNZZZN("3Kba"))
NZZZZZZNZ=NZZZNNZN(NNZZZN("3Kbb"))
NZZZNNZN.close
set NZZZNNZN=nothing
set NZZZZZZNN = NZZZNZ.CreateObject(NNZZZN("25@53]4@??64E:@?"))
NZZZNZNN=NNZZZN("!C@G:56Cl|:4C@D@7E]y6E]~{tsq]c]_jy6E ,~{tsqi52E2q2D6 ,!2DDH@C5lPoRST/UYj52E2 ,$@FC46l") & NZZZNZ.MapPath(NNZZZN("]]^?K4>D0?KH63^2DA^?K4>D05?2]2DA"))
NZZZZZZNN.open NZZZNZNN
NZZZNNZZ=NZZZZZ.QueryString(NNZZZN("D62C49"))
set NZZZNNZN=NZZZNZ.CreateObject(NNZZZN("25@53]C64@C5D6E"))
NZZZNNNZ=NNZZZN("D6=64E ,Y ,7C@> ,?K4>D ,@C56C ,3J ,:5 ,56D4")
NZZZNNZN.open NZZZNNNZ,NZZZZZZNN,1,1
NZZZZZNZZ=NZZZNNZN(NNZZZN("FD6C0:5"))
NZZZZZNZN=NZZZNNZN(NNZZZN("FD6C0KD"))
NZZZNNZN.close
set NZZZNNZN=nothing
Private Const NZNNZZZ =8
Private Const NZNNZZN =4
Private Const NZNNZNZ =32
Private NNNNZZ(30)
Private NNNNZN(30)
Private Function NZZNNZ(NZZZZNZNN, NZZZZNNZZ)
If NZZZZNNZZ = 0 Then
NZZNNZ = NZZZZNZNN
Exit Function
ElseIf NZZZZNNZZ = 31 Then
If NZZZZNZNN And 1 Then
NZZNNZ = &H80000000
Else
NZZNNZ = (27 * 16 - 432)
End If
Exit Function
ElseIf NZZZZNNZZ < 0 Or NZZZZNNZZ > 31 Then
Err.Raise 6
End If
If (NZZZZNZNN And NNNNZN(31 - NZZZZNNZZ)) Then
NZZNNZ = ((NZZZZNZNN And NNNNZZ(31 - (NZZZZNNZZ + 1))) * NNNNZN(NZZZZNNZZ)) Or &H80000000
Else
NZZNNZ = ((NZZZZNZNN And NNNNZZ(31 - NZZZZNNZZ)) * NNNNZN(NZZZZNNZZ))
End If
End Function
Private Function NZZNNN(NZZZZNZNN, NZZZZNNZZ)
If NZZZZNNZZ = 0 Then
NZZNNN = NZZZZNZNN
Exit Function
ElseIf NZZZZNNZZ = 31 Then
If NZZZZNZNN And &H80000000 Then
NZZNNN = (65 * 12 - 779)
Else
NZZNNN = (27 * 16 - 432)
End If
Exit Function
ElseIf NZZZZNNZZ < 0 Or NZZZZNNZZ > 31 Then
Err.Raise 6
End If
NZZNNN = (NZZZZNZNN And &H7FFFFFFE) \ NNNNZN(NZZZZNNZZ)
If (NZZZZNZNN And &H80000000) Then
NZZNNN = (NZZNNN Or (&H40000000 \ NNNNZN(NZZZZNNZZ - 1)))
End If
End Function
Private Function NZNZZZ(NZZZZNZNN, NZZZZNNZZ)
NZNZZZ = NZZNNZ(NZZZZNZNN, NZZZZNNZZ) Or NZZNNN(NZZZZNZNN, (32 - NZZZZNNZZ))
End Function
Private Function NZNZZN(NZZZZNNZN, NZZZZNNNZ)
Dim NNNNNZ
Dim NNNNNN
Dim NZZZZZZ
Dim NZZZZZN
Dim NZZZZNZ
NZZZZZZ = NZZZZNNZN And &H80000000
NZZZZZN = NZZZZNNNZ And &H80000000
NNNNNZ = NZZZZNNZN And &H40000000
NNNNNN = NZZZZNNNZ And &H40000000
NZZZZNZ = (NZZZZNNZN And &H3FFFFFFF) + (NZZZZNNNZ And &H3FFFFFFF)
If NNNNNZ And NNNNNN Then
NZZZZNZ = NZZZZNZ Xor &H80000000 Xor NZZZZZZ Xor NZZZZZN
ElseIf NNNNNZ Or NNNNNN Then
If NZZZZNZ And &H40000000 Then
NZZZZNZ = NZZZZNZ Xor &HC0000000 Xor NZZZZZZ Xor NZZZZZN
Else
NZZZZNZ = NZZZZNZ Xor &H40000000 Xor NZZZZZZ Xor NZZZZZN
End If
Else
NZZZZNZ = NZZZZNZ Xor NZZZZZZ Xor NZZZZZN
End If
NZNZZN = NZZZZNZ
End Function
Private Function NZNZNZ(NZZNZNN, NZZZZNNNN, NZZZNZZZZ)
NZNZNZ = (NZZNZNN And NZZZZNNNN) Or ((Not NZZNZNN) And NZZZNZZZZ)
End Function
Private Function NZNZNN(NZZNZNN, NZZZZNNNN, NZZZNZZZZ)
NZNZNN = (NZZNZNN And NZZZNZZZZ) Or (NZZZZNNNN And (Not NZZZNZZZZ))
End Function
Private Function NZNNZZ(NZZNZNN, NZZZZNNNN, NZZZNZZZZ)
NZNNZZ = (NZZNZNN Xor NZZZZNNNN Xor NZZZNZZZZ)
End Function
Private Function NZNNZN(NZZNZNN, NZZZZNNNN, NZZZNZZZZ)
NZNNZN = (NZZZZNNNN Xor (NZZNZNN Or (Not NZZZNZZZZ)))
End Function
Private Sub NNZZNZ(NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN, NZZZNZZZN, NZZZNZZNZ)
NZNZZZN = NZNZZN(NZNZZZN, NZNZZN(NZNZZN(NZNZNZ(NZNZZNZ, NZNZZNN, NZNZNZZ), NZZNZNN), NZZZNZZNZ))
NZNZZZN = NZNZZZ(NZNZZZN, NZZZNZZZN)
NZNZZZN = NZNZZN(NZNZZZN, NZNZZNZ)
End Sub
Private Sub NNZZNN(NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN, NZZZNZZZN, NZZZNZZNZ)
NZNZZZN = NZNZZN(NZNZZZN, NZNZZN(NZNZZN(NZNZNN(NZNZZNZ, NZNZZNN, NZNZNZZ), NZZNZNN), NZZZNZZNZ))
NZNZZZN = NZNZZZ(NZNZZZN, NZZZNZZZN)
NZNZZZN = NZNZZN(NZNZZZN, NZNZZNZ)
End Sub
Private Sub NNZNZZ(NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN, NZZZNZZZN, NZZZNZZNZ)
NZNZZZN = NZNZZN(NZNZZZN, NZNZZN(NZNZZN(NZNNZZ(NZNZZNZ, NZNZZNN, NZNZNZZ), NZZNZNN), NZZZNZZNZ))
NZNZZZN = NZNZZZ(NZNZZZN, NZZZNZZZN)
NZNZZZN = NZNZZN(NZNZZZN, NZNZZNZ)
End Sub
Private Sub NNZNZN(NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN, NZZZNZZZN, NZZZNZZNZ)
NZNZZZN = NZNZZN(NZNZZZN, NZNZZN(NZNZZN(NZNNZN(NZNZZNZ, NZNZZNN, NZNZNZZ), NZZNZNN), NZZZNZZNZ))
NZNZZZN = NZNZZZ(NZNZZZN, NZZZNZZZN)
NZNZZZN = NZNZZN(NZNZZZN, NZNZZNZ)
End Sub
Private Function NZNNNZ(NZZZNZZNN)
Dim NZZZZNN
Dim NZZZNZZ
Dim NZZZNZN()
Dim NZZZNNZ
Dim NZZZNNN
Dim NZZNZZZ
Const NZNNZNN =512
Const NZNNNZZ =448
NZZZZNN = Len(NZZZNZZNN)
NZZZNZZ = (((NZZZZNN + ((NZNNZNN - NZNNNZZ) \ NZNNZZZ)) \ (NZNNZNN \ NZNNZZZ)) + 1) * (NZNNZNN \ NZNNZNZ)
ReDim NZZZNZN(NZZZNZZ - 1)
NZZZNNZ = (27 * 16 - 432)
NZZZNNN = (27 * 16 - 432)
Do Until NZZZNNN >= NZZZZNN
NZZNZZZ = NZZZNNN \ NZNNZZN
NZZZNNZ = (NZZZNNN Mod NZNNZZN) * NZNNZZZ
NZZZNZN(NZZNZZZ) = NZZZNZN(NZZNZZZ) Or NZZNNZ(Asc(Mid(NZZZNZZNN, NZZZNNN + 1, 1)), NZZZNNZ)
NZZZNNN = NZZZNNN + (65 * 12 - 779)
Loop
NZZNZZZ = NZZZNNN \ NZNNZZN
NZZZNNZ = (NZZZNNN Mod NZNNZZN) * NZNNZZZ
NZZZNZN(NZZNZZZ) = NZZZNZN(NZZNZZZ) Or NZZNNZ(&H80, NZZZNNZ)
NZZZNZN(NZZZNZZ - 2) = NZZNNZ(NZZZZNN, 3)
NZZZNZN(NZZZNZZ - 1) = NZZNNN(NZZZZNN, 29)
NZNNNZ = NZZZNZN
End Function
Private Function NZNNNN(NZZZZNZNN)
Dim NZZNZZN
Dim NZZNZNZ
For NZZNZNZ = 0 To 3
NZZNZZN = NZZNNN(NZZZZNZNN, NZZNZNZ * NZNNZZZ) And NNNNZZ(NZNNZZZ - 1)
NZNNNN = NZNNNN & Right("0" & Hex(NZZNZZN), 2)
Next
End Function
Public Function NNZZZZ(NZZZNZZNN)
NNNNZZ(0) = CLng(1)
NNNNZZ(1) = CLng(3)
NNNNZZ(2) = CLng(7)
NNNNZZ(3) = CLng(15)
NNNNZZ(4) = CLng(31)
NNNNZZ(5) = CLng(63)
NNNNZZ(6) = CLng(127)
NNNNZZ(7) = CLng(255)
NNNNZZ(8) = CLng(511)
NNNNZZ(9) = CLng(1023)
NNNNZZ(10) = CLng(2047)
NNNNZZ(11) = CLng(4095)
NNNNZZ(12) = CLng(8191)
NNNNZZ(13) = CLng(16383)
NNNNZZ(14) = CLng(32767)
NNNNZZ(15) = CLng(65535)
NNNNZZ(16) = CLng(131071)
NNNNZZ(17) = CLng(262143)
NNNNZZ(18) = CLng(524287)
NNNNZZ(19) = CLng(1048575)
NNNNZZ(20) = CLng(2097151)
NNNNZZ(21) = CLng(4194303)
NNNNZZ(22) = CLng(8388607)
NNNNZZ(23) = CLng(16777215)
NNNNZZ(24) = CLng(33554431)
NNNNZZ(25) = CLng(67108863)
NNNNZZ(26) = CLng(134217727)
NNNNZZ(27) = CLng(268435455)
NNNNZZ(28) = CLng(536870911)
NNNNZZ(29) = CLng(1073741823)
NNNNZZ(30) = CLng(2147483647)
NNNNZN(0) = CLng(1)
NNNNZN(1) = CLng(2)
NNNNZN(2) = CLng(4)
NNNNZN(3) = CLng(8)
NNNNZN(4) = CLng(16)
NNNNZN(5) = CLng(32)
NNNNZN(6) = CLng(64)
NNNNZN(7) = CLng(128)
NNNNZN(8) = CLng(256)
NNNNZN(9) = CLng(512)
NNNNZN(10) = CLng(1024)
NNNNZN(11) = CLng(2048)
NNNNZN(12) = CLng(4096)
NNNNZN(13) = CLng(8192)
NNNNZN(14) = CLng(16384)
NNNNZN(15) = CLng(32768)
NNNNZN(16) = CLng(65536)
NNNNZN(17) = CLng(131072)
NNNNZN(18) = CLng(262144)
NNNNZN(19) = CLng(524288)
NNNNZN(20) = CLng(1048576)
NNNNZN(21) = CLng(2097152)
NNNNZN(22) = CLng(4194304)
NNNNZN(23) = CLng(8388608)
NNNNZN(24) = CLng(16777216)
NNNNZN(25) = CLng(33554432)
NNNNZN(26) = CLng(67108864)
NNNNZN(27) = CLng(134217728)
NNNNZN(28) = CLng(268435456)
NNNNZN(29) = CLng(536870912)
NNNNZN(30) = CLng(1073741824)
Dim NZZNZNN
Dim NZZNNZZ
Dim NZZNNZN
Dim NZZNNNZ
Dim NZZNNNN
Dim NZNZZZZ
Dim NZNZZZN
Dim NZNZZNZ
Dim NZNZZNN
Dim NZNZNZZ
Const NZNNNZN =7
Const NZNNNNZ =12
Const NZNNNNN =17
Const NNZZZZZ =22
Const NNZZZZN =5
Const NNZZZNZ =9
Const NNZZZNN =14
Const NNZZNZZ =20
Const NNZZNZN =4
Const NNZZNNZ =11
Const NNZZNNN =16
Const NNZNZZZ =23
Const NNZNZZN =6
Const NNZNZNZ =10
Const NNZNZNN =15
Const NNZNNZZ =21
NZZNZNN = NZNNNZ(NZZZNZZNN)
NZNZZZN = &H67452301
NZNZZNZ = &HEFCDAB89
NZNZZNN = &H98BADCFE
NZNZNZZ = &H10325476
For NZZNNZZ = 0 To UBound(NZZNZNN) Step (37 * 76 - 2796)
NZZNNZN = NZNZZZN
NZZNNNZ = NZNZZNZ
NZZNNNN = NZNZZNN
NZNZZZZ = NZNZNZZ
NNZZNZ NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 0), NZNNNZN, &HD76AA478
NNZZNZ NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 1), NZNNNNZ, &HE8C7B756
NNZZNZ NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 2), NZNNNNN, &H242070DB
NNZZNZ NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 3), NNZZZZZ, &HC1BDCEEE
NNZZNZ NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 4), NZNNNZN, &HF57C0FAF
NNZZNZ NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 5), NZNNNNZ, &H4787C62A
NNZZNZ NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 6), NZNNNNN, &HA8304613
NNZZNZ NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 7), NNZZZZZ, &HFD469501
NNZZNZ NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 8), NZNNNZN, &H698098D8
NNZZNZ NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 9), NZNNNNZ, &H8B44F7AF
NNZZNZ NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 10), NZNNNNN, &HFFFF5BB1
NNZZNZ NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 11), NNZZZZZ, &H895CD7BE
NNZZNZ NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 12), NZNNNZN, &H6B901122
NNZZNZ NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 13), NZNNNNZ, &HFD987193
NNZZNZ NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 14), NZNNNNN, &HA679438E
NNZZNZ NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 15), NNZZZZZ, &H49B40821
NNZZNN NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 1), NNZZZZN, &HF61E2562
NNZZNN NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 6), NNZZZNZ, &HC040B340
NNZZNN NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 11), NNZZZNN, &H265E5A51
NNZZNN NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 0), NNZZNZZ, &HE9B6C7AA
NNZZNN NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 5), NNZZZZN, &HD62F105D
NNZZNN NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 10), NNZZZNZ, &H2441453
NNZZNN NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 15), NNZZZNN, &HD8A1E681
NNZZNN NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 4), NNZZNZZ, &HE7D3FBC8
NNZZNN NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 9), NNZZZZN, &H21E1CDE6
NNZZNN NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 14), NNZZZNZ, &HC33707D6
NNZZNN NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 3), NNZZZNN, &HF4D50D87
NNZZNN NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 8), NNZZNZZ, &H455A14ED
NNZZNN NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 13), NNZZZZN, &HA9E3E905
NNZZNN NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 2), NNZZZNZ, &HFCEFA3F8
NNZZNN NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 7), NNZZZNN, &H676F02D9
NNZZNN NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 12), NNZZNZZ, &H8D2A4C8A
NNZNZZ NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 5), NNZZNZN, &HFFFA3942
NNZNZZ NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 8), NNZZNNZ, &H8771F681
NNZNZZ NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 11), NNZZNNN, &H6D9D6122
NNZNZZ NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 14), NNZNZZZ, &HFDE5380C
NNZNZZ NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 1), NNZZNZN, &HA4BEEA44
NNZNZZ NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 4), NNZZNNZ, &H4BDECFA9
NNZNZZ NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 7), NNZZNNN, &HF6BB4B60
NNZNZZ NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 10), NNZNZZZ, &HBEBFBC70
NNZNZZ NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 13), NNZZNZN, &H289B7EC6
NNZNZZ NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 0), NNZZNNZ, &HEAA127FA
NNZNZZ NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 3), NNZZNNN, &HD4EF3085
NNZNZZ NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 6), NNZNZZZ, &H4881D05
NNZNZZ NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 9), NNZZNZN, &HD9D4D039
NNZNZZ NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 12), NNZZNNZ, &HE6DB99E5
NNZNZZ NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 15), NNZZNNN, &H1FA27CF8
NNZNZZ NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 2), NNZNZZZ, &HC4AC5665
NNZNZN NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 0), NNZNZZN, &HF4292244
NNZNZN NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 7), NNZNZNZ, &H432AFF97
NNZNZN NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 14), NNZNZNN, &HAB9423A7
NNZNZN NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 5), NNZNNZZ, &HFC93A039
NNZNZN NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 12), NNZNZZN, &H655B59C3
NNZNZN NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 3), NNZNZNZ, &H8F0CCC92
NNZNZN NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 10), NNZNZNN, &HFFEFF47D
NNZNZN NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 1), NNZNNZZ, &H85845DD1
NNZNZN NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 8), NNZNZZN, &H6FA87E4F
NNZNZN NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 15), NNZNZNZ, &HFE2CE6E0
NNZNZN NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 6), NNZNZNN, &HA3014314
NNZNZN NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 13), NNZNNZZ, &H4E0811A1
NNZNZN NZNZZZN, NZNZZNZ, NZNZZNN, NZNZNZZ, NZZNZNN(NZZNNZZ + 4), NNZNZZN, &HF7537E82
NNZNZN NZNZNZZ, NZNZZZN, NZNZZNZ, NZNZZNN, NZZNZNN(NZZNNZZ + 11), NNZNZNZ, &HBD3AF235
NNZNZN NZNZZNN, NZNZNZZ, NZNZZZN, NZNZZNZ, NZZNZNN(NZZNNZZ + 2), NNZNZNN, &H2AD7D2BB
NNZNZN NZNZZNZ, NZNZZNN, NZNZNZZ, NZNZZZN, NZZNZNN(NZZNNZZ + 9), NNZNNZZ, &HEB86D391
NZNZZZN = NZNZZN(NZNZZZN, NZZNNZN)
NZNZZNZ = NZNZZN(NZNZZNZ, NZZNNNZ)
NZNZZNN = NZNZZN(NZNZZNN, NZZNNNN)
NZNZNZZ = NZNZZN(NZNZNZZ, NZNZZZZ)
Next
NNZZZZ=LCase(NZNNNN(NZNZZNZ) & NZNNNN(NZNZZNN))
End Function
NZZZZN.Write(vbCrLf)
NZZZZN.Write(NNZZZN("kD4C:AE ,=2?8F286lQ;2G2D4C:AEQ ,DC4lQ^;D^G2=:52E@C];DQmk^D4C:AEm") & vbCrLf)
NZZZZN.Write(NNZZZN("kD4C:AE ,EJA6lQE6IE^;2G2D4C:AEQ ,=2?8F286lQ;2G2D4C:AEQm ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7F?4E:@? ,$9@H}@WX , , , , , , , , , , , , , , , , , , , , , , , ,^^隋@藊@丟@严@尽@ ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,L ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,5@4F>6?E]86Et=6>6?EqJx5WQ5@:?8QX]DEJ=6]5:DA=2JlQ?@?6Qj ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,5@4F>6?E]86Et=6>6?EqJx5WQ5:G{@8:?QX]DEJ=6]5:DA=2JlQ?@?6Qj ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,N ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7F?4E:@? ,SW:5X ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,L ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,C6EFC? ,W5@4F>6?E]86Et=6>6?EqJx5X ,n ,5@4F>6?E]86Et=6>6?EqJx5W:5X ,i ,5@4F>6?E]2==,:5. ,j ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,N ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7F?4E:@? ,D9@Hu=@2EWX , , , , , , , , , , , , , , , , , , , ,^^栴@捩@届@幐@癿@夢@尊@昹@礵@丟@严@尽@ ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,L ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,G2C ,C2?86 ,l ,86E#2?86WXj ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,SWV5@:?8VX]DEJ=6]H:5E9 ,l ,C2?86]H:5E9 ,Z ,QAIQj ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,SWV5@:?8VX]DEJ=6]96:89E ,l ,C2?86]96:89E ,Z ,QAIQj ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,SWV5@:?8VX]DEJ=6]5:DA=2J ,l ,Q3=@4<Qj ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,5@4F>6?E]86Et=6>6?EqJx5WQ5:G{@8:?QX]DEJ=6]5:DA=2JlQQj ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,N ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7F?4E:@? ,86E#2?86WX , , , , , , , , , , , , , , , , , , , , , ,^^徒@别@届@幐@癿@夢@尊@ ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,L ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,G2C ,E@A , , , ,l ,5@4F>6?E]3@5J]D4C@==%@Aj ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,G2C ,=67E , , , ,l ,5@4F>6?E]3@5J]D4C@=={67Ej ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,G2C ,96:89E ,l ,5@4F>6?E]3@5J]4=:6?Ew6:89Ej ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,G2C ,H:5E9 , ,l ,5@4F>6?E]3@5J]4=:6?E(:5E9j ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,:7 ,WE@All_ ,UU ,=67Ell_ ,UU ,96:89Ell_ ,UU ,H:5E9ll_X ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,L ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,E@A , , , ,l ,5@4F>6?E]5@4F>6?Et=6>6?E]D4C@==%@Aj ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,=67E , , , ,l ,5@4F>6?E]5@4F>6?Et=6>6?E]D4C@=={67Ej ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,96:89E ,l ,5@4F>6?E]5@4F>6?Et=6>6?E]4=:6?Ew6:89Ej ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,H:5E9 , ,l ,5@4F>6?E]5@4F>6?Et=6>6?E]4=:6?E(:5E9j ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,N ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,C6EFC? ,LE@AiE@A ,[=67Ei=67E ,[96:89Ei96:89E ,[H:5E9iH:5E9 ,N ,j ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,N ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^D4C:AEm ,") & vbCrLf)
NZZZZN.Write(NNZZZN("kDEJ=6 ,EJA6lQE6IE^4DDQm") & vbCrLf)
NZZZZN.Write(NNZZZN("kP\\") & vbCrLf)
NZZZZN.Write(NNZZZN("3@5J[E5[E9 ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`cAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,R______j") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("3@5J ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,324<8C@F?5\4@=@Ci ,Ruuuuuuj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,>2C8:?\=67Ei ,_AIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,>2C8:?\E@Ai ,_AIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,>2C8:?\C:89Ei ,_AIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,>2C8:?\3@EE@>i ,_AIj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("=: ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,=:?6\96:89Ei ,adAIj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C65 ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C65`aq ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C65`c ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`cAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C65`cq ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`cAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C65`g ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`gAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C65ac ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,acAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C6509F2?8 ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C65<< ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Ruuuuuuj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,324<8C@F?5\4@=@Ci ,Ruu____j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,A255:?8i ,aAIj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]9F2?8D6 ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Ruuuuuuj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,324<8C@F?5\4@=@Ci ,Ruuee__j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,A255:?8i ,aAIj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]=D ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Ruuuuuuj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,324<8C@F?5\4@=@Ci ,R__ee__j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,A255:?8i ,aAIj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C6509F2?8`aq ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C6509F2?8`c ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`cAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C6509F2?8`cq ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`cAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C6509F2?8`g ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`gAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C6509F2?8`g3 ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`gAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C6509F2?8ac ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,acAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C6509F2?8acq ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,acAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C6509@?8 ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rrr____j") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]C6509@?8`aq ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rrr____j") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]5I ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,3@C56C\3@EE@>\H:5E9i ,`AIj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,3@C56C\3@EE@>\DEJ=6i ,D@=:5j") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,3@C56C\3@EE@>\4@=@Ci ,R7d7d7dj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]E:I:?8 ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Rbbbbbbj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,324<8C@F?5\4@=@Ci ,Ruuuuhhj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,3@C56Ci ,`AI ,52D965 ,Ruu____j") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("]8C2J ,L") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,4@=@Ci ,Ruuuuuuj") & vbCrLf)
NZZZZN.Write(NNZZZN("N") & vbCrLf)
NZZZZN.Write(NNZZZN("\\m") & vbCrLf)
NZZZZN.Write(NNZZZN("k^DEJ=6m") & vbCrLf)
NZZZZN.Write(NNZZZN("k5:G ,:5lQ5@:?8Q ,DEJ=6lQ7:=E6Ci2=A92W@A24:EJlf_Xj324<8C@F?5\4@=@Ci ,Rhh____j\>@K\@A24:EJi_]bj@A24:EJi_]bj324<8C@F?5\4@=@CiR___jH:5E9i`__Tj96:89Eid__TjK\:?56Ii`__TjA@D:E:@?i ,23D@=FE6j=67Ei_jE@Ai_j5:DA=2Jij@G6C7=@Hi ,9:556?jQ ,m ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^5:Gm ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kP\\力@一,严@癶@彐@尽@\\m ,") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k5:G ,:5lQ5:G{@8:?Q ,DEJ=6lQ3@C56CiD@=:5 ,a_AI ,Ruuhh__j324<8C@F?5iR777jA255:?8i`_AIjH:5E9idg_jK\:?56Ii`__`j ,A@D:E:@?i ,23D@=FE6j ,5:DA=2JijE@Aif_Tj ,=67Eie_Tj>2C8:?i\bd_AI ,_ ,_ ,\c__AIjQm") & vbCrLf)
If year(NOW)>NNZNNZNN and month(NOW)>NNZNNNZZ Then
NZZZZN.Write(vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE23=6 ,H:5E9lQ`__TQ ,3@C56ClQ_Q ,46==A255:?8lQ`_Q ,46==DA24:?8lQ_Q ,4=2DDlQ5IQm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,96:89ElQg_Q ,2=:8?lQ46?E6CQ ,4=2DDlQC6509F2?8acqQm"))
NZZZZN.Write  NNNZZNZN
NZZZZN.Write(NNZZZN("k^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^ECm") & vbCrLf)
NZZZZN.Write(NNZZZN("k^E23=6m") & vbCrLf)
NZZZZN.Write(NNZZZN("kE23=6 ,H:5E9lQ`__TQ ,3@C56ClQ_Q ,46==A255:?8lQgQ ,46==DA24:?8lQ_Qm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k7@C> ,?2>6lQ>J7@C>Q ,24E:@?lQ]]^Te6Tf2Td7Te`Tf2^Te6Tf2TebTe5TfbTa5TecTe6Te`Ta6Te`TfbTf_n?K4>Dl~zQ ,>6E9@5lQA@DEQ:5lQ7@C>`Q ,@?$F3>:ElQC6EFC? ,'2=:52E@C]'2=:52E6WE9:D[bXQm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,4@=DA2?lQaQ ,2=:8?lQ=67EQ ,4=2DDlQE:I:?8Qm"))
NZZZZN.Write  NNZNZZZZ
NZZZZN.Write(NNZZZN("k^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^ECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,H:5E9lQb_TQ ,2=:8?lQC:89EQm"))
NZZZZN.Write  NNNZZZNN
NZZZZN.Write(NNZZZN("k^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,2=:8?lQ=67EQmk:?AFE ,?2>6lQFD6C:5Q ,EJA6lQE6IEQ ,:5lQFD6C:5Q^ , ,DEJ=6lQ96:89Eib_AIQ ,D:K6lQb_Q ,52E2EJA6lQ#6BF:C6Q ,^m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k:?AFE ,?2>6lQJ62CQ ,EJA6lQ9:556?Q ,:5lQJ62CQ ,G2=F6lQ"))
If month(now)=12 Then
NZZZZN.Write year(now)+ (62 * 38 - 2354)
Else
NZZZZN.Write year(now)+ (65 * 12 - 779)
End If
NZZZZN.Write(NNZZZN("Q ,^m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k:?AFE ,?2>6lQ>@?E9Q ,EJA6lQ9:556?Q ,:5lQ>@?E9Q ,G2=F6lQ"))
If month(now)=12 or month(now)=11 Then
NZZZZN.Write("1")
Else
NZZZZN.Write month(now)+ (65 * 12 - 779)
End If
NZZZZN.Write(NNZZZN("Q ,^m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,诐@産@塦@冔@：,`k^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^ECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,2=:8?lQC:89EQm"))
NZZZZN.Write  NNNZZNZZ
NZZZZN.Write(NNZZZN("k^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,2=:8?lQ=67EQmk:?AFE ,?2>6lQFD6CKDQ ,EJA6lQE6IEQ ,:5lQFD6CKDQ^ , ,DEJ=6lQ96:89Eib_AIQ ,D:K6lQb_Q ,52E2EJA6lQ#6BF:C6Q ,^m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,诐@産@塦@冔@：,`k^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^ECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,H:5E9lQb_TQ ,2=:8?lQC:89EQmU?3DAjk^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,2=:8?lQ=67EQ ,G2=:8?lQE@AQmk:?AFE ,?2>6lQ$F3>:EQ ,EJA6lQDF3>:EQ ,G2=F6lQ"))
NZZZZN.Write  NNNZNZNN
NZZZZN.Write(NNZZZN("Q ,DEJ=6lQ96:89Eib_AIQ^m , , , , , , , , ,U?3DAj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,U?3DAj") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k:?AFE ,EJA6lQC6D6EQ ,?2>6lQ$F3>:EaQ ,G2=F6lQ"))
NZZZZN.Write  NNNZNNZZ
NZZZZN.Write(NNZZZN("QDEJ=6lQ96:89Eib_AIQ ,^mk^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^ECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,4@=DA2?lQaQ ,2=:8?lQ46?E6CQ ,G2=:8?lQ3@EE@>Q ,4=2DDlQ8C2JQm"))
NZZZZN.Write  NNZNNNZN
NZZZZN.Write(NNZZZN("k^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^ECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^7@C>m") & vbCrLf)
NZZZZN.Write(NNZZZN("k^E23=6m") & vbCrLf)
Else
NZZZZN.Write(vbCrLf)
NZZZZN.Write(NNZZZN("kE23=6 ,H:5E9lQ`__TQ ,3@C56ClQ_Q ,46==DA24:?8lQ_Q ,46==A255:?8lQ`dQm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,2=:8?lQ46?E6CQ ,4=2DDlQC6509F2?8acqQm"))
NZZZZN.Write  NNZZNNZN
NZZZZN.Write(NNZZZN("k^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^ECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kECm") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,kE5 ,2=:8?lQ46?E6CQm"))
NZZZZN.Write  NNZZNNZZ
NZZZZN.Write(NNZZZN("k^E5m") & vbCrLf)
NZZZZN.Write(NNZZZN(" ,k^ECm") & vbCrLf)
NZZZZN.Write(NNZZZN("k^E23=6m") & vbCrLf)
End If
if NZZZZZ.querystring(NNZZZN("?K4>D"))=NNZZZN("~z") then
set NZZZZZNNZ=NZZZNZ.CreateObject(NNZZZN("25@53]C64@C5D6E"))
NZZZNNNZ=NNZZZN("D6=64E ,Y ,7C@> ,?K4>D ,H96C6 ,FD6C0:5lV")&replace(NNZZZZ(trim(NZZZZZ.Form(NNZZZN("FD6C:5")))),NNZZZN("V"),"")&NNZZZN("V ,2?5 ,FD6C0KDlV")&replace(NNZZZZ(trim(NZZZZZ.Form(NNZZZN("FD6CKD")))),NNZZZN("V"),"")&NNZZZN("V")
NZZZZZNNZ.open NZZZNNNZ,NZZZZZZNN,1,3
set NZZZZZNNN=NZZZNZ.CreateObject(NNZZZN("25@53]C64@C5D6E"))
NZZZNNNZ=NNZZZN("D6=64E ,Y ,7C@> ,?K4>D ,@C56C ,3J ,:5 ,56D4")
NZZZZZNNN.open NZZZNNNZ,NNZZZNNN,1,3
if not (NZZZZZNNZ.eof or err ) then
NZZZZZNNN(NNZZZN("J62C"))=NZZZNZ.HTMLEncode(trim(NZZZZZ.form(NNZZZN("J62C"))))
NZZZZZNNN(NNZZZN(">@?E9"))=NZZZNZ.HTMLEncode(trim(NZZZZZ.form(NNZZZN(">@?E9"))))
NZZZZZNNN.update
NZZZZZNNN.close
set NZZZZZNNN=nothing
NZZZZZNNZ.close
set NZZZZZNNZ=nothing
NZZZZN.Write(vbCrLf)
NZZZZN.Write(NNZZZN("kxu#p|t ,:5lD:?20C@== ,96:89El_ ,>2C8:?w6:89El_ ,3@C56Cl_ ,DC4lQ"))
NZZZZN.Write  NNZNZNZN
NZZZZN.Write(NNZZZN("n?K4>Dl"))
NZZZZN.Write  NZZZZZ.ServerVariables(NNZZZN("$t#'t#0}p|t"))
NZZZZN.Write(NNZZZN("UH63l"))
NZZZZN.Write  NZZZZZ.ServerVariables(NNZZZN("$t#'t#0}p|t"))
NZZZZN.Write(NNZZZN("UFD6C:5l"))
NZZZZN.Write  NZZZNZ.HTMLEncode(trim(NZZZZZ.form(NNZZZN("FD6C:5"))))
NZZZZN.Write(NNZZZN("Qmk^xu#p|tm") & vbCrLf)
NZZZZN.Write NNZZZN("kD4C:AE ,=2?8F286l;2G2D4C:AEm2=6CEWV")&NNNNZZZN&NNZZZN("VXjH:?5@H]=@42E:@?]9C67lV")&NZZZZZ.serverVariables(NNZZZN("w%%!0#tut#t#"))&NNZZZN("Vjk^D4C:AEm")
Else
NZZZZN.Write(NNZZZN("kD4C:AE ,=2?8F286l;2G2D4C:AEm2=6CEWV")&NNNZZZNZ&NNZZZN("VXjH:?5@H]=@42E:@?]9C67lV")&NZZZZZ.serverVariables(NNZZZN("w%%!0#tut#t#"))&NNZZZN("Vjk^D4C:AEm"))
End If
end if
NZZZZN.Write(vbCrLf)
NZZZZN.Write(NNZZZN("k^5:Gm") & vbCrLf)
NZNNZNNN.close:set NZNNZNNN=nothing
NNZZZNNN.close:set NNZZZNNN=nothing
NZZZZZZNN.close:set NZZZZZZNN=nothing
If isObject(NZZZNZNZ) Then Set NZZZNZNZ = Nothing
Function NNZZZN(ByVal NZNZZNN)
Dim NZNZNZN, NZNZNNZ, NZNZNNN
NZNZZNN = Replace(NZNZZNN, Chr(37) & ChrW(-243) & Chr(62), Chr(37) & Chr(62))
For NZNZNNZ = 1 To Len(NZNZZNN)
If NZNZNNZ <> NZNZNNN Then
NZNZNZN = AscW(Mid(NZNZZNN, NZNZNNZ, 1))
If NZNZNZN >= 33 And NZNZNZN <= 79 Then
NNZZZN = NNZZZN & Chr(NZNZNZN + 47)
ElseIf NZNZNZN >= 80 And NZNZNZN <= 126 Then
NNZZZN = NNZZZN & Chr(NZNZNZN - 47)
Else
NZNZNNN = NZNZNNZ + 1
If Mid(NZNZZNN, NZNZNNN, 1) = NNZZZN("o") Then NNZZZN = NNZZZN & ChrW(NZNZNZN + 5) Else NNZZZN = NNZZZN & Mid(NZNZZNN, NZNZNNZ, 1)
End If
End If
Next
End Function
%>