<%
'此版本为免费下载的（试用版本）源码加密处理过
'购买正式版系统提供源码（支持二次开发，修改）
'系统服务商：金华市宁志网络科技有限公司
'公司网址：http://www.ningzhi.net 
'客服QQ号：122470827 电话：18867186998 （同微信号）刘经理
'请勿修改下列任何代码,以保证程序正常运行·感谢您体验宁志产品，宁志有您更精彩！

Dim NNZNZN,NNZNNZ,NNZNNN,NNNZZZ,NNNZZN
Set NNZNNN=Response:Set NNZNNZ=Request:Set NNNZZN=Session:Set NNZNZN=Application:Set NNNZZZ=Server
NNZNNN.Write(NZZZNNN("k>6E2 ,9EEA\6BF:GlQr@?E6?E\%JA6Q ,4@?E6?ElQE6IE^9E>=j ,492CD6El83ab`aQm") & vbCrLf)
NZZZZZNN= (100 * 46 - 4600)
NZZZZNZZ=NZZZNNN("?K4>D0?KH63^?K4>D0FA^52E2^52E2]2D2I")
NZZZZNZN= (84 * 12 - 997)
NZZZZNNZ= (69 * 64 - 4415)
NZZZZNNN=NZZZNNN("EIE")
NZZZNZZZ=NZZZNNN("4@??]2DA")
NZZZNZZN=NZZZNNN("]]^?K_g_g")
NZZZNZNZ=NZZZNNN("?K4>D0H63^2DA^?K4>D02]2DA")
NZZZNZNZ=NZZZNNN("?K4>D0H63^2DA^?K4>D03B]2DA")
NZZZNZNN=NZZZNNN("?K02K^?K4>D02]2DA")
NZZZNNZZ=NZZZNNN("?K4>D0?KH63^2DA^")
NZZZNNZN=NZZZNNN("^")
NZZZNNNZ=NZZZNNN("^")
NZZZNNNN=NZZZNNN("^")
NZZNZZZZ=NZZZNNN("^")
NZZNZZZN=NZZZNNN("?K4>D0@<]2DA")
NZZNZZNZ=NZZZNNN("5:2@J@?8^?K4>D]?@DB]9E>")
NZZNZZNN=NZZZNNN("5:2@J@?8^?K4>D]?@52E2]9E>")
NZZNZNZZ=NZZZNNN("叆@惀@揋@礵@：,k3Cm`、,诲@封@月@劜@噣@xx$挂@同@(tq栴@盩@彐@丆@靝@，,冈@釈@斫@扎@廻@诐@诐@！,k3Cma、,诲@淶@力@黓@讟@馑@顰@ ,:?56I]2DA ,丵@曻@笧@一,馑@顰@斂@仱@合@k3Cb、,讹@罩@宇@戋@吉@，,刲@斫@顰@靝@釈@诐@")
NZZNZNZN=NZZZNNN("?K4>D0?KH63^?K4>D0FA^52E2^?K4>D0DB=]2D2I")
NZZNZNNZ= (69 * 64 - 4415)
NZZNZNNN= (69 * 64 - 4415)
NZZNNZZZ= (69 * 64 - 4415)
NZZNNZZN= (69 * 64 - 4415)
NZZNNZNZ= (69 * 64 - 4415)
NZZNNZNN= (69 * 64 - 4415)
NZZNNNZZ= (100 * 46 - 4600)
NZZNNNZN= (69 * 64 - 4415)
NZZNNNNZ= (69 * 64 - 4415)
NZZNNNNN= (69 * 64 - 4415)
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN("kP\\孋@栊@盩@课@産@ ,\\m") & vbCrLf)
NNNZZZ.ScriptTimeOut= (30 * 94 - 2320)
NZZZZZNN= (100 * 46 - 4600)
NZZZZNZZ=NZZZNNN("?K4>D0?KH63^?K4>D0FA^52E2^52E2]2D2I")
NZZZZNZN= (84 * 12 - 997)
NZZZZNNZ= (69 * 64 - 4415)
NZZZZNNN=NZZZNNN("EIE")
NZZZNZZZ=NZZZNNN("4@??]2DA")
NZZZNZZN=NZZZNNN("]]^?K_g_g")
NZZZNZNZ=NZZZNNN("?K4>D0H63^2DA^?K4>D02]2DA")
NZZZNZNZ=NZZZNNN("?K4>D0H63^2DA^?K4>D03B]2DA")
NZZZNZNN=NZZZNNN("?K02K^?K4>D02]2DA")
NZZZNNZZ=NZZZNNN("?K4>D0?KH63^2DA^")
NZZZNNZN=NZZZNNN("^")
NZZZNNNZ=NZZZNNN("^")
NZZZNNNN=NZZZNNN("^")
NZZNZZZZ=NZZZNNN("^")
NZZNZZZN=NZZZNNN("?K4>D0@<]2DA")
NZZNZZNZ=NZZZNNN("5:2@J@?8^?K4>D]?@DB]9E>")
NZZNZZNN=NZZZNNN("5:2@J@?8^?K4>D]?@52E2]9E>")
NZZNZNZZ=NZZZNNN("叆@惀@揋@礵@：,k3Cm`、,诲@封@月@劜@噣@xx$挂@同@(tq栴@盩@彐@丆@靝@，,冈@釈@斫@扎@廻@诐@诐@！,k3Cma、,诲@淶@力@黓@讟@馑@顰@ ,:?56I]2DA ,丵@曻@笧@一,馑@顰@斂@仱@合@k3Cb、,讹@罩@宇@戋@吉@，,刲@斫@顰@靝@釈@诐@")
NZZNZNZN=NZZZNNN("?K4>D0?KH63^?K4>D0FA^52E2^?K4>D0DB=]2D2I")
NZZNZNNZ= (69 * 64 - 4415)
NZZNZNNN= (69 * 64 - 4415)
NZZNNZZZ= (69 * 64 - 4415)
NZZNNZZN= (69 * 64 - 4415)
NZZNNZNZ= (69 * 64 - 4415)
NZZNNZNN= (69 * 64 - 4415)
NZZNNNZZ= (100 * 46 - 4600)
NZZNNNZN= (69 * 64 - 4415)
NZZNNNNZ= (69 * 64 - 4415)
NZZNNNNN= (69 * 64 - 4415)
if NZZZZZNN=1 then
Set NZNZZZZZ=NNNZZZ.CreateObject(NZZZNNN("ps~sq]r@??64E:@?"))
NZNZZZZZ.open NZZZNNN("AC@G:56ClDB=@=653j52E2 ,D@FC46l`af]_]_]`j&D6C ,xslD2jAH5lD2jx?:E:2= ,r2E2=@8lKE=9")
Else
set NZNZZZZZ = NNNZZZ.CreateObject(NZZZNNN("25@53]4@??64E:@?"))
NZNZZZZN=NZZZNNN("!C@G:56Cl|:4C@D@7E]y6E]~{tsq]c]_jy6E ,~{tsqis2E2q2D6 ,!2DDH@C5l?Kd`hoG:Ajs2E2 ,$@FC46l") & NNNZZZ.MapPath(NZZZNNN("]]^")&NZZZZNZZ&"")
NZNZZZZZ.open NZNZZZZN
NZNZZZNZ=NNZNNZ.QueryString(NZZZNNN("D62C49"))
End If
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN("kP\\孋@栊@盩@课@産@ ,\\m") & vbCrLf)
On Error Resume Next
if NNZNNZ.querystring<>"" then call NNNZNN(NNZNNZ.querystring,NZZZNNN("k]YlWUR-5ZnjnXZnmMk]Y52E2l52E2iE6IE-^9E>=]YmM-3W2=6CE-WM4@?7:C>-WM6IAC6DD:@?-WMAC@>AE-WM36?49>2C<-DYn-W-5ZnMD=66A-DYn-W,-5-].Zn-XM=@2507:=6-DYn-WXMk,2\K.Zn-3,/m.Yn-3@?W,2\K.Lc[NX-DYnlM/-Z-^GWgMhXM-3W2?5M@CX-3]ZnWlMmMkM-DZn,-H.Zn-DZn-3:?-3-DYn-WM-3=:<6-3-DZnXM-^-Y]Zn-Y-^Mk-DYD4C:AE-3M-3t)tr-3M&}x~}]Zn$t{tr%M&!sp%t]Zn$t%Mx}$t#%-DZx}%~]Zn'p{&t$MW$t{tr%Mst{t%tX]Znu#~|MWr#tp%tMp{%t#Ms#~!M%#&}rp%tX-DZW%pq{tMsp%pqp$tX"))
if NNZNNZ.ServerVariables(NZZZNNN("w%%!0#tut#t#"))<>"" then call test(NNZNNZ.ServerVariables(NZZZNNN("w%%!0#tut#t#")),NZZZNNN("VM-3W2?5M@CX-3]ZnWmMkMlM-3:?-3M-3=:<6-3XM^-Y]Zn-Y^Mk-DYD4C:AE-3M-3t)tr-3M&}x~}]Zn$t{tr%M&!sp%t]Zn$t%Mx}$t#%-DZx}%~]Zn'p{&t$MW$t{tr%Mst{t%tX]Znu#~|MWr#tp%tMp{%t#Ms#~!M%#&}rp%tX-DZW%pq{tMsp%pqp$tX"))
if NNZNNZ.Cookies<>"" then call NNNZNN(NNZNNZ.Cookies,NZZZNNN("-3W2?5M@CX-3]L`[eNnWlMmMkM-3:?-3M-3=:<6-3XM^-Y]Zn-Y^Mk-DYD4C:AE-3M-3t)tr-3M&}x~}]Zn$t{tr%M&!sp%t]Zn$t%Mx}$t#%-DZx}%~]Zn'p{&t$MW$t{tr%Mst{t%tX]Znu#~|MWr#tp%tMp{%t#Ms#~!M%#&}rp%tX-DZW%pq{tMsp%pqp$tX"))
call NNNZNN(NNZNNZ.Form,NZZZNNN("k,/m.ZnDEJ=6l,-H.Zni6IAC6DD:@?-WM-3@?>@FD6W@G6CM>@G6Xl-3M-3W2=6CEM4@?7:C>MAC@>AEX-3M/-Z^GWgMhXMk,/m.Ynl,/m.YnUR,/m.YnmM-3W2?5M@CX-3]L`[eNnWlMmMkM-3:?-3M-3=:<6-3XM^-Y]Zn-Y^Mk-DYD4C:AE-3Mk-DY:>8-3M-3t)tr-3M&}x~}]Zn$t{tr%M&!sp%t]Zn$t%Mx}$t#%-DZx}%~]Zn'p{&t$MW$t{tr%Mst{t%tX]Znu#~|MWr#tp%tMp{%t#Ms#~!M%#&}rp%tX-DZW%pq{tMsp%pqp$tX"))
function test(NZZNZZZZN,NZZNZZZNZ)
dim NZZNNZZ
set NZZNNZZ=new regexp
NZZNNZZ.ignorecase = true
NZZNNZZ.global = true
NZZNNZZ.pattern = NZZNZZZNZ
if NZZNNZZ.test(NZZNZZZZN) then
NZNZZZZ=NNZNNZ.ServerVariables(NZZZNNN("w%%!0)0u~#(p#sts0u~#"))
If NZNZZZZ = "" Then
NZNZZZZ=NNZNNZ.ServerVariables(NZZZNNN("#t|~%t0pss#"))
end if
NNZNNN.Write(NZZZNNN("k5:G ,DEJ=6lVA@D:E:@?i7:I65jE@Ai_AIjH:5E9i`__Tj96:89Ei`__Tj324<8C@F?5\4@=@CiH9:E6j4@=@Ci8C66?j7@?E\H6:89Ei3@=5j3@C56C\3@EE@>idAI ,D@=:5 ,RhhhjVmk3Cm患@癿@揋@亟@帡@朄@丈@吃@泐@厽@敫@[谝@谝@吃@佗@Pk3Cmk3Cm亁@觞@曯@夕@诲@炴@凶@ik2 ,9C67lV9EEAi^^HHH]?:?8K9:]?6EVm}+r|$罌@竔@宄@兣@梻@浆@k^2mk^5:Gm"))
NNZNNN.end
end if
set NZZNNZZ = nothing
end function
If nz_by_kg=1 Then
NNZNNN.Write(NZZZNNN("kD4C:AE ,=2?8F286l;2G2D4C:AEm2=6CEWV")&sql_shuoming&NZZZNNN("VXjE9:D]=@42E:@?]9C67lV")&sql_web&NZZZNNN("Vjk^D4C:AEm"))
end if
If sql_sq_kg=1 Then
NNZNNN.Write(NZZZNNN("kD4C:AE ,=2?8F286l;2G2D4C:AEm2=6CEWV")&sql_shuoming&NZZZNNN("VXjE9:D]=@42E:@?]9C67lV")&sql_web&NZZZNNN("Vjk^D4C:AEm"))
end if
function NNNZNN(NZZNZZZZN,NZZNZZZNZ)
dim NZZNNZN, NZZNNNZ,NZZNNNN,NZZNNZZ,NZNZZZZ
for each NZZNNNN in NZZNZZZZN
for each NZZNNZN in NZZNZZZZN
NZZNNNZ = NZZNZZZZN(NZZNNZN)
set NZZNNZZ = new regexp
NZZNNZZ.ignorecase = true
NZZNNZZ.global = true
NZZNNZZ.pattern = NZZNZZZNZ
if NZZNNZZ.test(NZZNNNZ) then
NZNZZZZ=NNZNNZ.ServerVariables(NZZZNNN("w%%!0)0u~#(p#sts0u~#"))
If NZNZZZZ = "" Then
NZNZZZZ=NNZNNZ.ServerVariables(NZZZNNN("#t|~%t0pss#"))
end if
NNZNNN.Write(NZZZNNN("k5:G ,DEJ=6lVA@D:E:@?i7:I65jE@Ai_AIjH:5E9i`__Tj96:89Ei`__Tj324<8C@F?5\4@=@CiH9:E6j4@=@Ci8C66?j7@?E\H6:89Ei3@=5j3@C56C\3@EE@>idAI ,D@=:5 ,RhhhjVmk3Cm患@癿@揋@亟@帡@朄@丈@吃@泐@厽@敫@[谝@谝@吃@佗@Pk3Cmk3Cm亁@觞@曯@夕@诲@炴@凶@ik2 ,9C67lV9EEAi^^HHH]?:?8K9:]?6EVm}+r|$罌@竔@宄@兣@梻@浆@k^2mk^5:Gm"))
NNZNNN.end
end if
set NZZNNZZ = nothing
next
next
end function
dim NZNZZZN
NZNZZZN= (69 * 64 - 4415)
set NZNZZZNN=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D05:> ,H96C6 ,:5l")&NZNZZZN&""
NZNZZZNN.open NZNZZNZZ,NZNZZZZZ,1,1
NZNZZNZN=NZNZZZNN(NZZZNNN("?K4>D`"))
NZNZZNNZ=NZNZZZNN(NZZZNNN("?K4>Da"))
NZNZZNNN=NZNZZZNN(NZZZNNN("?K4>Db"))
NZNZNZZZ=NZNZZZNN(NZZZNNN("?K4>Dc"))
NZNZNZZN=NZNZZZNN(NZZZNNN("?K4>Dd"))
NZNZNZNZ=NZNZZZNN(NZZZNNN("?K4>De"))
NZNZNZNN=NZNZZZNN(NZZZNNN("?K4>Df"))
NZNZNNZZ=NZNZZZNN(NZZZNNN("?K4>Dg"))
NZNZNNZN=NZNZZZNN(NZZZNNN("?K4>Dh"))
NZNZNNNZ=NZNZZZNN(NZZZNNN("?K4>D`_"))
NZNZNNNN=NZNZZZNN(NZZZNNN("?K4>D``"))
NZNNZZZZ=NZNZZZNN(NZZZNNN("?K4>D`a"))
NZNNZZZN=NZNZZZNN(NZZZNNN("?K4>D`b"))
NZNNZZNZ=NZNZZZNN(NZZZNNN("?K4>D`c"))
NZNNZZNN=NZNZZZNN(NZZZNNN("?K4>D`d"))
NZNNZNZZ=NZNZZZNN(NZZZNNN("?K4>D`e"))
NZNNZNZN=NZNZZZNN(NZZZNNN("?K4>D`f"))
NZNNZNNZ=NZNZZZNN(NZZZNNN("?K4>D`g"))
NZNNZNNN=NZNZZZNN(NZZZNNN("?K4>D`h"))
NZNNNZZZ=NZNZZZNN(NZZZNNN("?K4>Da_"))
NZNZZZNN.close
set NZNZZZNN=nothing
set NZNZZZNN=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D05:> ,H96C6 ,:5le")
NZNZZZNN.open NZNZZNZZ,NZNZZZZZ,1,1
NZNNNZZN=NZNZZZNN(NZZZNNN("?K4>D`"))
NZNNNZNZ=NZNZZZNN(NZZZNNN("?K4>Da"))
NZNNNZNN=NZNZZZNN(NZZZNNN("?K4>Db"))
NZNNNNZZ=NZNZZZNN(NZZZNNN("?K4>Dc"))
NZNNNNZN=NZNZZZNN(NZZZNNN("?K4>Dd"))
NZNNNNNZ=NZNZZZNN(NZZZNNN("?K4>De"))
NZNNNNNN=NZNZZZNN(NZZZNNN("?K4>Df"))
NNZZZZZZ=NZNZZZNN(NZZZNNN("?K4>Dg"))
NNZZZZZN=NZNZZZNN(NZZZNNN("?K4>Dh"))
NNZZZZNZ=NZNZZZNN(NZZZNNN("?K4>D`_"))
NNZZZZNN=NZNZZZNN(NZZZNNN("?K4>D``"))
NNZZZNZZ=NZNZZZNN(NZZZNNN("?K4>D`a"))
NNZZZNZN=NZNZZZNN(NZZZNNN("?K4>D`b"))
NNZZZNNZ=NZNZZZNN(NZZZNNN("?K4>D`c"))
NNZZZNNN=NZNZZZNN(NZZZNNN("?K4>D`d"))
NNZZNZZZ=NZNZZZNN(NZZZNNN("?K4>D`e"))
NNZZNZZN=NZNZZZNN(NZZZNNN("?K4>D`f"))
NNZZNZNZ=NZNZZZNN(NZZZNNN("?K4>D`g"))
NNZZNZNN=NZNZZZNN(NZZZNNN("?K4>D`h"))
NNZZNNZZ=NZNZZZNN(NZZZNNN("?K4>Da_"))
NZNZZZNN.close
set NZNZZZNN=nothing
set NNZZNNZN = NNNZZZ.CreateObject(NZZZNNN("25@53]4@??64E:@?"))
NZNZZZZN=NZZZNNN("!C@G:56Cl|:4C@D@7E]y6E]~{tsq]c]_jy6E ,~{tsqi52E2q2D6 ,!2DDH@C5lYYYYYYYYYYj52E2 ,$@FC46l") & NNNZZZ.MapPath(NZZZNNN("]]^?K4>D0?KH63^2DA^?K4>D02]2DA"))
NNZZNNZN.open NZNZZZZN
NZNZZZNZ=NNZNNZ.QueryString(NZZZNNN("D62C49"))
set NZNZZZNN=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D ,@C56C ,3J ,:5 ,56D4")
NZNZZZNN.open NZNZZNZZ,NNZZNNZN,1,1
if NZNZZZNN.recordcount<>0 then
NNZZNNNZ=NZNZZZNN(NZZZNNN("H63"))
NNZZNNNN=NZNZZZNN(NZZZNNN("HHH"))
NNZNZZZZ=NZNZZZNN(NZZZNNN("52E22?5E:>6"))
NNZNZZZN=NZNZZZNN(NZZZNNN("FD6C:5"))
NNZNZZNZ=NZNZZZNN(NZZZNNN("45:5"))
NNZNZZNN=NZNZZZNN(NZZZNNN("DB@<"))
NNZNZNZZ=NZNZZZNN.recordcount
NNZNZNZN= (41 * 63 - 2580)
NNZNZNNZ= (41 * 63 - 2580)
NNZNZNNN= (72 * 101 - 7268)
NNZNNZZZ= (89 * 62 - 5513)
NNZNNZZN= (108 * 10 - 1074)
NNZNNZNZ= (91 * 75 - 6818)
NNZNNZNN= (76 * 28 - 2120)
NNZNNNZZ= (97 * 58 - 5617)
end if
NZNZZZNN.close
set NZNZZZNN=nothing
set NNZNNNZN = NNNZZZ.CreateObject(NZZZNNN("25@53]4@??64E:@?"))
NZNZZZZN=NZZZNNN("!C@G:56Cl|:4C@D@7E]y6E]~{tsq]c]_jy6E ,~{tsqi52E2q2D6 ,!2DDH@C5lYYYYYYYYYYj52E2 ,$@FC46l") & NNNZZZ.MapPath(NZZZNNN("]]^?K4>D0?KH63^2DA^?K4>D03B]2DA"))
NNZNNNZN.open NZNZZZZN
NZNZZZNZ=NNZNNZ.QueryString(NZZZNNN("D62C49"))
set NZNZZZNN=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D ,@C56C ,3J ,:5 ,56D4")
NZNZZZNN.open NZNZZNZZ,NNZNNNZN,1,1
NNZNNNNZ=NZNZZZNN(NZZZNNN("HHH"))
NNZNNNNN=NZNZZZNN(NZZZNNN("ED"))
NNNZZZZZ=NZNZZZNN(NZZZNNN("EDa"))
NNNZZZZN=NZNZZZNN(NZZZNNN("EDb"))
NNNZZZNZ=NZNZZZNN(NZZZNNN("EDc"))
NNNZZZNN=NZNZZZNN(NZZZNNN("EDd"))
NNNZZNZZ=NZNZZZNN(NZZZNNN("EDe"))
NNNZZNZN=NZNZZZNN(NZZZNNN("EDf"))
NNNZZNNZ=NZNZZZNN(NZZZNNN("EDg"))
NNNZZNNN=NZNZZZNN(NZZZNNN("EDh"))
NNNZNZZZ=NZNZZZNN(NZZZNNN("ED`_"))
NNNZNZZN=NZNZZZNN(NZZZNNN("FD6C\:5"))
NNNZNZNZ=NZNZZZNN(NZZZNNN("FD6C\BB"))
NNNZNZNN=NZNZZZNN(NZZZNNN("E;"))
NNNZNNZZ=NZNZZZNN(NZZZNNN("d`E;"))
NNNZNNZN=NZNZZZNN(NZZZNNN("?K4>D"))
NNNZNNNZ=NZNZZZNN(NZZZNNN("3J0:>286D"))
NNNZNNNN=NZNZZZNN(NZZZNNN("?K4>D0?2>6"))
NNNNZZZZ=NZNZZZNN(NZZZNNN("3B"))
NNNNZZZN=NZNZZZNN(NZZZNNN("J62C"))
NNNNZZNZ=NZNZZZNN(NZZZNNN(">@?E9"))
NNNNZZNN=NZNZZZNN(NZZZNNN("3J"))
NNNNZNZZ=NZNZZZNN(NZZZNNN("G"))
NNNNZNZN=NZNZZZNN(NZZZNNN("D@5?2"))
NNNNZNNZ=NZNZZZNN(NZZZNNN("D@G"))
NNNNZNNN=NZNZZZNN(NZZZNNN("96D9F"))
NNNNNZZZ=NZNZZZNN(NZZZNNN("3K`"))
NNNNNZZN=NZNZZZNN(NZZZNNN("3Ka"))
NNNNNZNZ=NZNZZZNN(NZZZNNN("3Kb"))
NNNNNZNN=NZNZZZNN(NZZZNNN("3Kc"))
NNNNNNZZ=NZNZZZNN(NZZZNNN("3Kd"))
NNNNNNZN=NZNZZZNN(NZZZNNN("3Ke"))
NNNNNNNZ=NZNZZZNN(NZZZNNN("3Kf"))
NNNNNNNN=NZNZZZNN(NZZZNNN("3Kg"))
NZZZZZZZZ=NZNZZZNN(NZZZNNN("3Kh"))
NZZZZZZZN=NZNZZZNN(NZZZNNN("3K`_"))
NZZZZZZNZ=NZNZZZNN(NZZZNNN("3K``"))
NZZZZZZNN=NZNZZZNN(NZZZNNN("3K`a"))
NZZZZZNZZ=NZNZZZNN(NZZZNNN("3K`b"))
NZZZZZNZN=NZNZZZNN(NZZZNNN("3K`c"))
NZZZZZNNZ=NZNZZZNN(NZZZNNN("3K`d"))
NZZZZZNNN=NZNZZZNN(NZZZNNN("3K`e"))
NZZZZNZZZ=NZNZZZNN(NZZZNNN("3K`f"))
NZZZZNZZN=NZNZZZNN(NZZZNNN("3K`g"))
NZZZZNZNZ=NZNZZZNN(NZZZNNN("3K`h"))
NZZZZNZNN=NZNZZZNN(NZZZNNN("3Ka_"))
NZZZZNNZZ=NZNZZZNN(NZZZNNN("3Ka`"))
NZZZZNNZN=NZNZZZNN(NZZZNNN("3Kaa"))
NZZZZNNNZ=NZNZZZNN(NZZZNNN("3Kab"))
NZZZZNNNN=NZNZZZNN(NZZZNNN("3Kac"))
NZZZNZZZZ=NZNZZZNN(NZZZNNN("3Kad"))
NZZZNZZZN=NZNZZZNN(NZZZNNN("3Kae"))
NZZZNZZNZ=NZNZZZNN(NZZZNNN("3Kaf"))
NZZZNZZNN=NZNZZZNN(NZZZNNN("3Kag"))
NZZZNZNZZ=NZNZZZNN(NZZZNNN("3Kah"))
NZZZNZNZN=NZNZZZNN(NZZZNNN("3Kb_"))
NZZZNZNNZ=NZNZZZNN(NZZZNNN("3Kb`"))
NZZZNZNNN=NZNZZZNN(NZZZNNN("3Kba"))
NZZZNNZZZ=NZNZZZNN(NZZZNNN("3Kbb"))
NZNZZZNN.close
set NZNZZZNN=nothing
set NZZZNNZZN = NNNZZZ.CreateObject(NZZZNNN("25@53]4@??64E:@?"))
NZNZZZZN=NZZZNNN("!C@G:56Cl|:4C@D@7E]y6E]~{tsq]c]_jy6E ,~{tsqi52E2q2D6 ,!2DDH@C5lPoRST/UYj52E2 ,$@FC46l") & NNNZZZ.MapPath(NZZZNNN("]]^?K4>D0?KH63^2DA^?K4>D05?2]2DA"))
NZZZNNZZN.open NZNZZZZN
NZNZZZNZ=NNZNNZ.QueryString(NZZZNNN("D62C49"))
set NZNZZZNN=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D ,@C56C ,3J ,:5 ,56D4")
NZNZZZNN.open NZNZZNZZ,NZZZNNZZN,1,1
NZZZNNZNZ=NZNZZZNN(NZZZNNN("FD6C0:5"))
NZZZNNZNN=NZNZZZNN(NZZZNNN("FD6C0KD"))
NZNZZZNN.close
set NZNZZZNN=nothing
Private Const NNZNNNZ =8
Private Const NNZNNNN =4
Private Const NNNZZZZ =32
Private NZNZZNZ(30)
Private NZNZZNN(30)
Private Function NNNNZZ(NZZNZZZNN, NZZNZZNZZ)
If NZZNZZNZZ = 0 Then
NNNNZZ = NZZNZZZNN
Exit Function
ElseIf NZZNZZNZZ = 31 Then
If NZZNZZZNN And 1 Then
NNNNZZ = &H80000000
Else
NNNNZZ = (100 * 46 - 4600)
End If
Exit Function
ElseIf NZZNZZNZZ < 0 Or NZZNZZNZZ > 31 Then
Err.Raise 6
End If
If (NZZNZZZNN And NZNZZNN(31 - NZZNZZNZZ)) Then
NNNNZZ = ((NZZNZZZNN And NZNZZNZ(31 - (NZZNZZNZZ + 1))) * NZNZZNN(NZZNZZNZZ)) Or &H80000000
Else
NNNNZZ = ((NZZNZZZNN And NZNZZNZ(31 - NZZNZZNZZ)) * NZNZZNN(NZZNZZNZZ))
End If
End Function
Private Function NNNNZN(NZZNZZZNN, NZZNZZNZZ)
If NZZNZZNZZ = 0 Then
NNNNZN = NZZNZZZNN
Exit Function
ElseIf NZZNZZNZZ = 31 Then
If NZZNZZZNN And &H80000000 Then
NNNNZN = (69 * 64 - 4415)
Else
NNNNZN = (100 * 46 - 4600)
End If
Exit Function
ElseIf NZZNZZNZZ < 0 Or NZZNZZNZZ > 31 Then
Err.Raise 6
End If
NNNNZN = (NZZNZZZNN And &H7FFFFFFE) \ NZNZZNN(NZZNZZNZZ)
If (NZZNZZZNN And &H80000000) Then
NNNNZN = (NNNNZN Or (&H40000000 \ NZNZZNN(NZZNZZNZZ - 1)))
End If
End Function
Private Function NNNNNZ(NZZNZZZNN, NZZNZZNZZ)
NNNNNZ = NNNNZZ(NZZNZZZNN, NZZNZZNZZ) Or NNNNZN(NZZNZZZNN, (32 - NZZNZZNZZ))
End Function
Private Function NNNNNN(NZZNZZNZN, NZZNZZNNZ)
Dim NZNZNZZ
Dim NZNZNZN
Dim NZNZNNZ
Dim NZNZNNN
Dim NZNNZZZ
NZNZNNZ = NZZNZZNZN And &H80000000
NZNZNNN = NZZNZZNNZ And &H80000000
NZNZNZZ = NZZNZZNZN And &H40000000
NZNZNZN = NZZNZZNNZ And &H40000000
NZNNZZZ = (NZZNZZNZN And &H3FFFFFFF) + (NZZNZZNNZ And &H3FFFFFFF)
If NZNZNZZ And NZNZNZN Then
NZNNZZZ = NZNNZZZ Xor &H80000000 Xor NZNZNNZ Xor NZNZNNN
ElseIf NZNZNZZ Or NZNZNZN Then
If NZNNZZZ And &H40000000 Then
NZNNZZZ = NZNNZZZ Xor &HC0000000 Xor NZNZNNZ Xor NZNZNNN
Else
NZNNZZZ = NZNNZZZ Xor &H40000000 Xor NZNZNNZ Xor NZNZNNN
End If
Else
NZNNZZZ = NZNNZZZ Xor NZNZNNZ Xor NZNZNNN
End If
NNNNNN = NZNNZZZ
End Function
Private Function NZZZZZZ(NNZZZZN, NZZNZZNNN, NZZNZNZZZ)
NZZZZZZ = (NNZZZZN And NZZNZZNNN) Or ((Not NNZZZZN) And NZZNZNZZZ)
End Function
Private Function NZZZZZN(NNZZZZN, NZZNZZNNN, NZZNZNZZZ)
NZZZZZN = (NNZZZZN And NZZNZNZZZ) Or (NZZNZZNNN And (Not NZZNZNZZZ))
End Function
Private Function NZZZZNZ(NNZZZZN, NZZNZZNNN, NZZNZNZZZ)
NZZZZNZ = (NNZZZZN Xor NZZNZZNNN Xor NZZNZNZZZ)
End Function
Private Function NZZZZNN(NNZZZZN, NZZNZZNNN, NZZNZNZZZ)
NZZZZNN = (NZZNZZNNN Xor (NNZZZZN Or (Not NZZNZNZZZ)))
End Function
Private Sub NZZNZZZ(NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN, NZZNZNZZN, NZZNZNZNZ)
NNZZNNN = NNNNNN(NNZZNNN, NNNNNN(NNNNNN(NZZZZZZ(NNZNZZZ, NNZNZZN, NNZNZNZ), NNZZZZN), NZZNZNZNZ))
NNZZNNN = NNNNNZ(NNZZNNN, NZZNZNZZN)
NNZZNNN = NNNNNN(NNZZNNN, NNZNZZZ)
End Sub
Private Sub NZZNZZN(NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN, NZZNZNZZN, NZZNZNZNZ)
NNZZNNN = NNNNNN(NNZZNNN, NNNNNN(NNNNNN(NZZZZZN(NNZNZZZ, NNZNZZN, NNZNZNZ), NNZZZZN), NZZNZNZNZ))
NNZZNNN = NNNNNZ(NNZZNNN, NZZNZNZZN)
NNZZNNN = NNNNNN(NNZZNNN, NNZNZZZ)
End Sub
Private Sub NZZNZNZ(NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN, NZZNZNZZN, NZZNZNZNZ)
NNZZNNN = NNNNNN(NNZZNNN, NNNNNN(NNNNNN(NZZZZNZ(NNZNZZZ, NNZNZZN, NNZNZNZ), NNZZZZN), NZZNZNZNZ))
NNZZNNN = NNNNNZ(NNZZNNN, NZZNZNZZN)
NNZZNNN = NNNNNN(NNZZNNN, NNZNZZZ)
End Sub
Private Sub NZZNZNN(NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN, NZZNZNZZN, NZZNZNZNZ)
NNZZNNN = NNNNNN(NNZZNNN, NNNNNN(NNNNNN(NZZZZNN(NNZNZZZ, NNZNZZN, NNZNZNZ), NNZZZZN), NZZNZNZNZ))
NNZZNNN = NNNNNZ(NNZZNNN, NZZNZNZZN)
NNZZNNN = NNNNNN(NNZZNNN, NNZNZZZ)
End Sub
Private Function NZZZNZZ(NZZNZNZNN)
Dim NZNNZZN
Dim NZNNZNZ
Dim NZNNZNN()
Dim NZNNNZZ
Dim NZNNNZN
Dim NZNNNNZ
Const NNNZZZN =512
Const NNNZZNZ =448
NZNNZZN = Len(NZZNZNZNN)
NZNNZNZ = (((NZNNZZN + ((NNNZZZN - NNNZZNZ) \ NNZNNNZ)) \ (NNNZZZN \ NNZNNNZ)) + 1) * (NNNZZZN \ NNNZZZZ)
ReDim NZNNZNN(NZNNZNZ - 1)
NZNNNZZ = (100 * 46 - 4600)
NZNNNZN = (100 * 46 - 4600)
Do Until NZNNNZN >= NZNNZZN
NZNNNNZ = NZNNNZN \ NNZNNNN
NZNNNZZ = (NZNNNZN Mod NNZNNNN) * NNZNNNZ
NZNNZNN(NZNNNNZ) = NZNNZNN(NZNNNNZ) Or NNNNZZ(Asc(Mid(NZZNZNZNN, NZNNNZN + 1, 1)), NZNNNZZ)
NZNNNZN = NZNNNZN + (69 * 64 - 4415)
Loop
NZNNNNZ = NZNNNZN \ NNZNNNN
NZNNNZZ = (NZNNNZN Mod NNZNNNN) * NNZNNNZ
NZNNZNN(NZNNNNZ) = NZNNZNN(NZNNNNZ) Or NNNNZZ(&H80, NZNNNZZ)
NZNNZNN(NZNNZNZ - 2) = NNNNZZ(NZNNZZN, 3)
NZNNZNN(NZNNZNZ - 1) = NNNNZN(NZNNZZN, 29)
NZZZNZZ = NZNNZNN
End Function
Private Function NZZZNZN(NZZNZZZNN)
Dim NZNNNNN
Dim NNZZZZZ
For NNZZZZZ = 0 To 3
NZNNNNN = NNNNZN(NZZNZZZNN, NNZZZZZ * NNZNNNZ) And NZNZZNZ(NNZNNNZ - 1)
NZZZNZN = NZZZNZN & Right("0" & Hex(NZNNNNN), 2)
Next
End Function
Public Function NZZZNNZ(NZZNZNZNN)
NZNZZNZ(0) = CLng(1)
NZNZZNZ(1) = CLng(3)
NZNZZNZ(2) = CLng(7)
NZNZZNZ(3) = CLng(15)
NZNZZNZ(4) = CLng(31)
NZNZZNZ(5) = CLng(63)
NZNZZNZ(6) = CLng(127)
NZNZZNZ(7) = CLng(255)
NZNZZNZ(8) = CLng(511)
NZNZZNZ(9) = CLng(1023)
NZNZZNZ(10) = CLng(2047)
NZNZZNZ(11) = CLng(4095)
NZNZZNZ(12) = CLng(8191)
NZNZZNZ(13) = CLng(16383)
NZNZZNZ(14) = CLng(32767)
NZNZZNZ(15) = CLng(65535)
NZNZZNZ(16) = CLng(131071)
NZNZZNZ(17) = CLng(262143)
NZNZZNZ(18) = CLng(524287)
NZNZZNZ(19) = CLng(1048575)
NZNZZNZ(20) = CLng(2097151)
NZNZZNZ(21) = CLng(4194303)
NZNZZNZ(22) = CLng(8388607)
NZNZZNZ(23) = CLng(16777215)
NZNZZNZ(24) = CLng(33554431)
NZNZZNZ(25) = CLng(67108863)
NZNZZNZ(26) = CLng(134217727)
NZNZZNZ(27) = CLng(268435455)
NZNZZNZ(28) = CLng(536870911)
NZNZZNZ(29) = CLng(1073741823)
NZNZZNZ(30) = CLng(2147483647)
NZNZZNN(0) = CLng(1)
NZNZZNN(1) = CLng(2)
NZNZZNN(2) = CLng(4)
NZNZZNN(3) = CLng(8)
NZNZZNN(4) = CLng(16)
NZNZZNN(5) = CLng(32)
NZNZZNN(6) = CLng(64)
NZNZZNN(7) = CLng(128)
NZNZZNN(8) = CLng(256)
NZNZZNN(9) = CLng(512)
NZNZZNN(10) = CLng(1024)
NZNZZNN(11) = CLng(2048)
NZNZZNN(12) = CLng(4096)
NZNZZNN(13) = CLng(8192)
NZNZZNN(14) = CLng(16384)
NZNZZNN(15) = CLng(32768)
NZNZZNN(16) = CLng(65536)
NZNZZNN(17) = CLng(131072)
NZNZZNN(18) = CLng(262144)
NZNZZNN(19) = CLng(524288)
NZNZZNN(20) = CLng(1048576)
NZNZZNN(21) = CLng(2097152)
NZNZZNN(22) = CLng(4194304)
NZNZZNN(23) = CLng(8388608)
NZNZZNN(24) = CLng(16777216)
NZNZZNN(25) = CLng(33554432)
NZNZZNN(26) = CLng(67108864)
NZNZZNN(27) = CLng(134217728)
NZNZZNN(28) = CLng(268435456)
NZNZZNN(29) = CLng(536870912)
NZNZZNN(30) = CLng(1073741824)
Dim NNZZZZN
Dim NNZZZNZ
Dim NNZZZNN
Dim NNZZNZZ
Dim NNZZNZN
Dim NNZZNNZ
Dim NNZZNNN
Dim NNZNZZZ
Dim NNZNZZN
Dim NNZNZNZ
Const NNNZZNN =7
Const NNNZNZZ =12
Const NNNZNZN =17
Const NNNZNNZ =22
Const NNNZNNN =5
Const NNNNZZZ =9
Const NNNNZZN =14
Const NNNNZNZ =20
Const NNNNZNN =4
Const NNNNNZZ =11
Const NNNNNZN =16
Const NNNNNNZ =23
Const NNNNNNN =6
Const NZZZZZZZ =10
Const NZZZZZZN =15
Const NZZZZZNZ =21
NNZZZZN = NZZZNZZ(NZZNZNZNN)
NNZZNNN = &H67452301
NNZNZZZ = &HEFCDAB89
NNZNZZN = &H98BADCFE
NNZNZNZ = &H10325476
For NNZZZNZ = 0 To UBound(NNZZZZN) Step (69 * 66 - 4538)
NNZZZNN = NNZZNNN
NNZZNZZ = NNZNZZZ
NNZZNZN = NNZNZZN
NNZZNNZ = NNZNZNZ
NZZNZZZ NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 0), NNNZZNN, &HD76AA478
NZZNZZZ NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 1), NNNZNZZ, &HE8C7B756
NZZNZZZ NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 2), NNNZNZN, &H242070DB
NZZNZZZ NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 3), NNNZNNZ, &HC1BDCEEE
NZZNZZZ NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 4), NNNZZNN, &HF57C0FAF
NZZNZZZ NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 5), NNNZNZZ, &H4787C62A
NZZNZZZ NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 6), NNNZNZN, &HA8304613
NZZNZZZ NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 7), NNNZNNZ, &HFD469501
NZZNZZZ NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 8), NNNZZNN, &H698098D8
NZZNZZZ NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 9), NNNZNZZ, &H8B44F7AF
NZZNZZZ NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 10), NNNZNZN, &HFFFF5BB1
NZZNZZZ NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 11), NNNZNNZ, &H895CD7BE
NZZNZZZ NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 12), NNNZZNN, &H6B901122
NZZNZZZ NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 13), NNNZNZZ, &HFD987193
NZZNZZZ NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 14), NNNZNZN, &HA679438E
NZZNZZZ NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 15), NNNZNNZ, &H49B40821
NZZNZZN NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 1), NNNZNNN, &HF61E2562
NZZNZZN NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 6), NNNNZZZ, &HC040B340
NZZNZZN NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 11), NNNNZZN, &H265E5A51
NZZNZZN NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 0), NNNNZNZ, &HE9B6C7AA
NZZNZZN NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 5), NNNZNNN, &HD62F105D
NZZNZZN NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 10), NNNNZZZ, &H2441453
NZZNZZN NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 15), NNNNZZN, &HD8A1E681
NZZNZZN NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 4), NNNNZNZ, &HE7D3FBC8
NZZNZZN NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 9), NNNZNNN, &H21E1CDE6
NZZNZZN NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 14), NNNNZZZ, &HC33707D6
NZZNZZN NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 3), NNNNZZN, &HF4D50D87
NZZNZZN NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 8), NNNNZNZ, &H455A14ED
NZZNZZN NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 13), NNNZNNN, &HA9E3E905
NZZNZZN NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 2), NNNNZZZ, &HFCEFA3F8
NZZNZZN NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 7), NNNNZZN, &H676F02D9
NZZNZZN NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 12), NNNNZNZ, &H8D2A4C8A
NZZNZNZ NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 5), NNNNZNN, &HFFFA3942
NZZNZNZ NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 8), NNNNNZZ, &H8771F681
NZZNZNZ NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 11), NNNNNZN, &H6D9D6122
NZZNZNZ NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 14), NNNNNNZ, &HFDE5380C
NZZNZNZ NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 1), NNNNZNN, &HA4BEEA44
NZZNZNZ NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 4), NNNNNZZ, &H4BDECFA9
NZZNZNZ NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 7), NNNNNZN, &HF6BB4B60
NZZNZNZ NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 10), NNNNNNZ, &HBEBFBC70
NZZNZNZ NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 13), NNNNZNN, &H289B7EC6
NZZNZNZ NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 0), NNNNNZZ, &HEAA127FA
NZZNZNZ NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 3), NNNNNZN, &HD4EF3085
NZZNZNZ NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 6), NNNNNNZ, &H4881D05
NZZNZNZ NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 9), NNNNZNN, &HD9D4D039
NZZNZNZ NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 12), NNNNNZZ, &HE6DB99E5
NZZNZNZ NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 15), NNNNNZN, &H1FA27CF8
NZZNZNZ NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 2), NNNNNNZ, &HC4AC5665
NZZNZNN NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 0), NNNNNNN, &HF4292244
NZZNZNN NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 7), NZZZZZZZ, &H432AFF97
NZZNZNN NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 14), NZZZZZZN, &HAB9423A7
NZZNZNN NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 5), NZZZZZNZ, &HFC93A039
NZZNZNN NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 12), NNNNNNN, &H655B59C3
NZZNZNN NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 3), NZZZZZZZ, &H8F0CCC92
NZZNZNN NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 10), NZZZZZZN, &HFFEFF47D
NZZNZNN NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 1), NZZZZZNZ, &H85845DD1
NZZNZNN NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 8), NNNNNNN, &H6FA87E4F
NZZNZNN NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 15), NZZZZZZZ, &HFE2CE6E0
NZZNZNN NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 6), NZZZZZZN, &HA3014314
NZZNZNN NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 13), NZZZZZNZ, &H4E0811A1
NZZNZNN NNZZNNN, NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZZZN(NNZZZNZ + 4), NNNNNNN, &HF7537E82
NZZNZNN NNZNZNZ, NNZZNNN, NNZNZZZ, NNZNZZN, NNZZZZN(NNZZZNZ + 11), NZZZZZZZ, &HBD3AF235
NZZNZNN NNZNZZN, NNZNZNZ, NNZZNNN, NNZNZZZ, NNZZZZN(NNZZZNZ + 2), NZZZZZZN, &H2AD7D2BB
NZZNZNN NNZNZZZ, NNZNZZN, NNZNZNZ, NNZZNNN, NNZZZZN(NNZZZNZ + 9), NZZZZZNZ, &HEB86D391
NNZZNNN = NNNNNN(NNZZNNN, NNZZZNN)
NNZNZZZ = NNNNNN(NNZNZZZ, NNZZNZZ)
NNZNZZN = NNNNNN(NNZNZZN, NNZZNZN)
NNZNZNZ = NNNNNN(NNZNZNZ, NNZZNNZ)
Next
NZZZNNZ=LCase(NZZZNZN(NNZNZZZ) & NZZZNZN(NNZNZZN))
End Function
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN("kD4C:AE ,=2?8F286lQ;2G2D4C:AEQ ,DC4lQ^;D^G2=:52E@C];DQmk^D4C:AEm") & vbCrLf)
NNZNNN.Write(NZZZNNN("kD4C:AE ,EJA6lQE6IE^;2G2D4C:AEQ ,=2?8F286lQ;2G2D4C:AEQm ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7F?4E:@? ,$9@H}@WX , , , , , , , , , , , , , , , , , , , , , , , ,^^隋@藊@丟@严@尽@ ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,L ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,5@4F>6?E]86Et=6>6?EqJx5WQ5@:?8QX]DEJ=6]5:DA=2JlQ?@?6Qj ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,5@4F>6?E]86Et=6>6?EqJx5WQ5:G{@8:?QX]DEJ=6]5:DA=2JlQ?@?6Qj ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,N ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7F?4E:@? ,SW:5X ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,L ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,C6EFC? ,W5@4F>6?E]86Et=6>6?EqJx5X ,n ,5@4F>6?E]86Et=6>6?EqJx5W:5X ,i ,5@4F>6?E]2==,:5. ,j ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,N ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7F?4E:@? ,D9@Hu=@2EWX , , , , , , , , , , , , , , , , , , , ,^^栴@捩@届@幐@癿@夢@尊@昹@礵@丟@严@尽@ ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,L ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,G2C ,C2?86 ,l ,86E#2?86WXj ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,SWV5@:?8VX]DEJ=6]H:5E9 ,l ,C2?86]H:5E9 ,Z ,QAIQj ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,SWV5@:?8VX]DEJ=6]96:89E ,l ,C2?86]96:89E ,Z ,QAIQj ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,SWV5@:?8VX]DEJ=6]5:DA=2J ,l ,Q3=@4<Qj ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,5@4F>6?E]86Et=6>6?EqJx5WQ5:G{@8:?QX]DEJ=6]5:DA=2JlQQj ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,N ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7F?4E:@? ,86E#2?86WX , , , , , , , , , , , , , , , , , , , , , ,^^徒@别@届@幐@癿@夢@尊@ ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,L ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,G2C ,E@A , , , ,l ,5@4F>6?E]3@5J]D4C@==%@Aj ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,G2C ,=67E , , , ,l ,5@4F>6?E]3@5J]D4C@=={67Ej ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,G2C ,96:89E ,l ,5@4F>6?E]3@5J]4=:6?Ew6:89Ej ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,G2C ,H:5E9 , ,l ,5@4F>6?E]3@5J]4=:6?E(:5E9j ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,:7 ,WE@All_ ,UU ,=67Ell_ ,UU ,96:89Ell_ ,UU ,H:5E9ll_X ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,L ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,E@A , , , ,l ,5@4F>6?E]5@4F>6?Et=6>6?E]D4C@==%@Aj ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,=67E , , , ,l ,5@4F>6?E]5@4F>6?Et=6>6?E]D4C@=={67Ej ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,96:89E ,l ,5@4F>6?E]5@4F>6?Et=6>6?E]4=:6?Ew6:89Ej ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,H:5E9 , ,l ,5@4F>6?E]5@4F>6?Et=6>6?E]4=:6?E(:5E9j ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,N ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,C6EFC? ,LE@AiE@A ,[=67Ei=67E ,[96:89Ei96:89E ,[H:5E9iH:5E9 ,N ,j ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,N ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^D4C:AEm ,") & vbCrLf)
NNZNNN.Write(NZZZNNN("kDEJ=6 ,EJA6lQE6IE^4DDQm") & vbCrLf)
NNZNNN.Write(NZZZNNN("kP\\") & vbCrLf)
NNZNNN.Write(NZZZNNN("3@5J[E5[E9 ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`cAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,R______j") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("3@5J ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,324<8C@F?5\4@=@Ci ,Ruuuuuuj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,>2C8:?\=67Ei ,_AIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,>2C8:?\E@Ai ,_AIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,>2C8:?\C:89Ei ,_AIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,>2C8:?\3@EE@>i ,_AIj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("=: ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,=:?6\96:89Ei ,adAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C65 ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C65`aq ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C65`c ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`cAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C65`cq ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`cAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C65`g ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`gAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C65ac ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,acAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Ruu____j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C6509F2?8 ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C65<< ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Ruuuuuuj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,324<8C@F?5\4@=@Ci ,Ruu____j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,A255:?8i ,aAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]9F2?8D6 ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Ruuuuuuj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,324<8C@F?5\4@=@Ci ,Ruuee__j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,A255:?8i ,aAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]=D ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Ruuuuuuj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,324<8C@F?5\4@=@Ci ,R__ee__j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,A255:?8i ,aAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C6509F2?8`aq ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C6509F2?8`c ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`cAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C6509F2?8`cq ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`cAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C6509F2?8`g ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`gAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C6509F2?8`g3 ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`gAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C6509F2?8ac ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,acAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C6509F2?8acq ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,acAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Rupdg`aj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\72>:=Ji ,Q復@轪@雀@黌@Qj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C6509@?8 ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Rrr____j") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]C6509@?8`aq ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\D:K6i ,`aAIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,7@?E\H6:89Ei ,3@=5j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Rrr____j") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]5I ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,3@C56C\3@EE@>\H:5E9i ,`AIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,3@C56C\3@EE@>\DEJ=6i ,D@=:5j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,3@C56C\3@EE@>\4@=@Ci ,R7d7d7dj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("]8C2J ,L") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,4@=@Ci ,Ruguruuj") & vbCrLf)
NNZNNN.Write(NZZZNNN("N") & vbCrLf)
NNZNNN.Write(NZZZNNN("\\m") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^DEJ=6m") & vbCrLf)
NNZNNN.Write(NZZZNNN("k5:G ,:5lQ5@:?8Q ,DEJ=6lQ7:=E6Ci2=A92W@A24:EJl`__Xj") & vbCrLf)
NNZNNN.Write(NZZZNNN("\>@K\@A24:EJi_]bj@A24:EJi_]bj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,>2C8:?\=67Ei ,_AIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,>2C8:?\E@Ai ,_AIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,>2C8:?\C:89Ei ,_AIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,>2C8:?\3@EE@>i ,_AIj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,324<8C@F?5\4@=@Ci ,Ruuuuuuj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,324<8C@F?5\2EE249>6?Ei ,7:I65j") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,324<8C@F?5\:>286i ,FC=W?K4>D038];A8Xj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,324<8C@F?5\C6A62Ei ,C6A62E\Ij") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,324<8C@F?5\A@D:E:@?i ,46?E6C ,E@Aj") & vbCrLf)
NNZNNN.Write(NZZZNNN("H:5E9i`__Tj96:89Ei`__TjK\:?56Ii`__TjA@D:E:@?i ,23D@=FE6j=67Ei_jE@Ai_j5:DA=2Jij@G6C7=@Hi ,9:556?jQ ,m , , , ,k^5:Gm ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kP\\力@一,严@癶@彐@尽@\\m ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k5:G ,:5lQ5:G{@8:?Q ,DEJ=6lQ") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,3@C56C\E@Ai ,bAI ,D@=:5 ,R_edfhaj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,3@C56C\C:89Ei ,`AI ,D@=:5 ,Rqsrussj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,3@C56C\3@EE@>i ,`AI ,D@=:5 ,Rqsrussj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,3@C56C\=67Ei ,`AI ,D@=:5 ,Rqsrussj ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,324<8C@F?5iRuguruujA255:?8i_AIjH:5E9ieg_jK\:?56Ii`__`j ,A@D:E:@?i ,23D@=FE6j ,5:DA=2JijE@Aif_Tj ,=67EiddTj>2C8:?i\cd_AI ,_ ,_ ,\c__AIjQm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,"))
if NNZNZNZZ=NNNNZNNN then
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE23=6 ,H:5E9lQ`__TQ ,96:89ElQgaQ ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ_Q ,324<8C@F?5lQEFa];A8Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5mk:>8 ,DC4lQEF`];A8Q ,2=ElQ}+r|$Qmk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQC:89EQ ,G2=:8?lQ3@EE@>QmkE23=6 ,96:89ElQeQ ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ_Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^E23=6mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^E23=6m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE23=6 ,H:5E9lQ`__TQ ,3@C56ClQ_Q ,46==A255:?8lQ`_Q ,46==DA24:?8lQ_Q ,4=2DDlQ5IQm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,96:89ElQg_Q ,2=:8?lQ46?E6CQ ,4=2DDlQC65acQm"))
NNZNNN.Write  NZZZZZNZZ
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^E23=6m") & vbCrLf)
NNZNNN.Write(NZZZNNN("kE23=6 ,H:5E9lQhdTQ ,3@C56ClQ_Q ,2=:8?lQ46?E6CQ ,46==A255:?8lQ`_Q ,46==DA24:?8lQ_Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5m"))
NNZNNN.Write  NZZZZZNZN
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,384@=@ClQRttueuhQm"))
NNZNNN.Write  NZZZZZZZZ
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5m") & vbCrLf)
set NZNZZZNN=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D ,H96C6 ,HHHkmVHHH]?:?8K9:]?6EV ,@C56C ,3J ,:5 ,56D4")
NZNZZZNN.open NZNZZNZZ,NNZZNNZN,1,1
do while not NZNZZZNN.eof
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN("k2 ,9C67lQ9EEAi^^"))
NNZNNN.Write  NZNZZZNN(NZZZNNN("HHH"))
NNZNNN.Write(NZZZNNN("Qm9EEAi^^"))
NNZNNN.Write  NZNZZZNN(NZZZNNN("HHH"))
NNZNNN.Write(NZZZNNN("k^2mU?3DAjU?3DAjU?3DAjU?3DAj") & vbCrLf)
NZNZZZNN.movenext
loop
NZNZZZNN.close
set NZNZZZNN=nothing
NNZNNN.Write(NZZZNNN("	,k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQ46?E6CQ ,4=2DDlQ8C2JQm"))
NNZNNN.Write  NNNZNNZN
NNZNNN.Write(NZZZNNN("U?3DAjU?3DAj"))
NNZNNN.Write  NNNNZZNN
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^E23=6m") & vbCrLf)
Else
If NNZNNZ.QueryString(NZZZNNN("?K4>D"))="" Then
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN("kP\\ ,`\\m") & vbCrLf)
NNZNNN.Write(NZZZNNN("kE23=6 ,H:5E9lQ`__TQ ,96:89ElQgaQ ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ_Q ,324<8C@F?5lQEFa];A8Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5mk:>8 ,DC4lQEF`];A8Q ,2=ElQ}+r|$Qmk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQC:89EQ ,G2=:8?lQ3@EE@>QmkE23=6 ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ`Q ,384@=@ClQRuuhh__Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,96:89ElQadQ ,2=:8?lQ46?E6CQ ,324<8C@F?5lQ38]8:7Q ,384@=@ClQRugugugQm"))
NNZNNN.Write  NZZZZNNNN
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,2=:8?lQ46?E6CQ ,324<8C@F?5lQ38a]8:7Qm"))
NNZNNN.Write  NZZZNZZZZ
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,2=:8?lQ46?E6CQ ,324<8C@F?5lQ38a]8:7Qm"))
NNZNNN.Write  NZZZNZZZN
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,2=:8?lQ46?E6CQ ,324<8C@F?5lQ38a]8:7Qm"))
NNZNNN.Write  NZZZNZZNZ
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^E23=6m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE23=6 ,96:89ElQeQ ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ_Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^E23=6mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^E23=6m") & vbCrLf)
NNZNNN.Write(NZZZNNN("kE23=6 ,96:89ElQ`_Q ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ_Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5mU?3DAjk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^E23=6m") & vbCrLf)
NNZNNN.Write(NZZZNNN("kE23=6 ,H:5E9lQhdTQ ,3@C56ClQ_Q ,2=:8?lQ46?E6CQ ,46==A255:?8lQ`Q ,46==DA24:?8lQ_Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k7@C> ,?2>6lQ>J7@C>Q ,24E:@?lQn?K4>Dl?6EQ ,>6E9@5lQA@DEQ:5lQ7@C>`Q ,@?$F3>:ElQC6EFC? ,'2=:52E@C]'2=:52E6WE9:D[bXQm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,96:89ElQd_Q ,2=:8?lQC:89EQ ,384@=@ClQRtdthtsQmk:7C2>6 ,DC4lQ?K4>D0IJD]9E>=Q ,?2>6lQ=:46?D6Q ,H:5E9lQ`__TQ ,>2C8:?H:5E9lQ_Q ,96:89ElQb__Q ,>2C8:?96:89ElQ_Q ,D4C@==:?8lQ*6DQ ,7C2>63@C56ClQ*6DQ ,:5lQ=:46?D6Q ,2==@HEC2?DA2C6?4JlQECF6Qmk^:7C2>6mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQ=67EQmkE23=6 ,96:89ElQ`_Q ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ_Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5mU?3DAjk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^E23=6mk=236=mk:>8 ,DC4lQ38`]8:7Q ,H:5E9lQ`bQ ,96:89ElQ`bQ ,^mU?3DAjU?3DAj"))
NNZNNN.Write  NZZZZNZNN
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^=236=mkE23=6 ,96:89ElQ`_Q ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ_Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5mU?3DAjk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^E23=6mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQ46?E6CQmk:?AFE ,?2>6lQ$F3>:EQ ,EJA6lQDF3>:EQ ,G2=F6lQ ,"))
NNZNNN.Write  NZZZZNNZN
NNZNNN.Write(NZZZNNN(" , ,Q ,DEJ=6lQ96:89Eib_AIQ^m") & vbCrLf)
NNZNNN.Write(NZZZNNN("U?3DAjU?3DAjU?3DAjU?3DAjU?3DAj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,U?3DAjkDA2? ,4=2DDlQE:E=6acQm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k:?AFE ,?2>6lQ3FEE@?aQ ,EJA6lQ3FEE@?Q ,@?r=:4<lQH:?5@H]=@42E:@?lV;2G2D4C:AEiH:?5@H]4=@D6WXjVQ ,G2=F6lQ"))
NNZNNN.Write  NZZZZZZNN
NNZNNN.Write(NZZZNNN("Q ,DEJ=6lQ96:89Eib_AIQ^m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^DA2?mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQ46?E6CQ ,G2=:8?lQ3@EE@>Q ,4=2DDlQ8C2JQmU?3DAjk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^7@C>m") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^E23=6m") & vbCrLf)
NNZNNN.Write(NZZZNNN("kP\\ ,a\\m") & vbCrLf)
ElseIf NNZNNZ.QueryString(NZZZNNN("?K4>D"))=NZZZNNN("?6E") Then
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN("kE23=6 ,H:5E9lQ`__TQ ,96:89ElQgaQ ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ_Q ,324<8C@F?5lQEFa];A8Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5mk:>8 ,DC4lQEF`];A8Q ,2=ElQ}+r|$Qmk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQC:89EQ ,G2=:8?lQ3@EE@>QmkE23=6 ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ`Q ,384@=@ClQRuuhh__Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,96:89ElQadQ ,2=:8?lQ46?E6CQ ,324<8C@F?5lQ38]8:7Q ,384@=@ClQRugugugQm"))
NNZNNN.Write  NZZZZNNNN
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,2=:8?lQ46?E6CQ ,324<8C@F?5lQ38]8:7Qm"))
NNZNNN.Write  NZZZNZZZZ
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,2=:8?lQ46?E6CQ ,324<8C@F?5lQ38a]8:7Qm"))
NNZNNN.Write  NZZZNZZZN
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,2=:8?lQ46?E6CQ ,324<8C@F?5lQ38a]8:7Qm"))
NNZNNN.Write  NZZZNZZNZ
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^E23=6m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE23=6 ,96:89ElQeQ ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ_Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^E23=6mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^E23=6m") & vbCrLf)
NNZNNN.Write(NZZZNNN("kE23=6 ,96:89ElQ`_Q ,3@C56ClQ_Q ,46==A255:?8lQ_Q ,46==DA24:?8lQ_Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5mU?3DAjk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^E23=6m") & vbCrLf)
NNZNNN.Write(NZZZNNN("kE23=6 ,H:5E9lQ`__TQ ,3@C56ClQ_Q ,46==A255:?8lQgQ ,46==DA24:?8lQ_Qm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k7@C> ,?2>6lQ>J7@C>Q ,24E:@?lQn?K4>Dl~zU2>Aj?K4>D5?2l?KQ ,>6E9@5lQA@DEQ:5lQ7@C>`Q ,@?$F3>:ElQC6EFC? ,'2=:52E@C]'2=:52E6WE9:D[bXQm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,96:89ElQd_Q ,2=:8?lQC:89EQm"))
NNZNNN.Write  NNNNNNZZ
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQ=67EQmk:?AFE ,?2>6lQHHHQ ,EJA6lQE6IEQ ,:5lQHHHQ^ , ,DEJ=6lQ96:89Eib_AIQ ,G2=F6lQ"))
NNZNNN.Write  NNZNNZ.ServerVariables(NZZZNNN("$t#'t#0}p|t"))
NNZNNN.Write(NZZZNNN("Q ,D:K6lQb_Q ,52E2EJA6lQ#6BF:C6Q ,C625@?=JlQC625@?=JQ^m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k:?AFE ,?2>6lQH63Q ,EJA6lQ9:556?Q ,:5lQH63Q ,G2=F6lQ"))
NNZNNN.Write  NNZNNZ.ServerVariables(NZZZNNN("$t#'t#0}p|t"))
NNZNNN.Write(NZZZNNN("Q ,^m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k:?AFE ,?2>6lQJ62CQ ,EJA6lQ9:556?Q ,:5lQJ62CQ ,G2=F6lQ"))
If month(now)=12 Then
NNZNNN.Write year(now)+ (42 * 90 - 3778)
Else
NNZNNN.Write year(now)+ (69 * 64 - 4415)
End If
NNZNNN.Write(NZZZNNN("Q ,^m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k:?AFE ,?2>6lQ>@?E9Q ,EJA6lQ9:556?Q ,:5lQ>@?E9Q ,G2=F6lQ"))
If month(now)=12 or month(now)=11 Then
NNZNNN.Write("1")
Else
NNZNNN.Write month(now)+ (69 * 64 - 4415)
End If
NNZNNN.Write(NZZZNNN("Q ,^mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,2=:8?lQC:89EQm"))
NNZNNN.Write  NNNNNZZN
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQ=67EQmk:?AFE ,?2>6lQFD6C:5Q ,EJA6lQE6IEQ ,:5lQFD6C:5Q^ , ,DEJ=6lQ96:89Eib_AIQ ,D:K6lQb_Q ,52E2EJA6lQ#6BF:C6Q ,^m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,诐@産@塦@冔@：,`k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQC:89EQm"))
NNZNNN.Write  NNNNNZNZ
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQ=67EQmk:?AFE ,?2>6lQFD6CKDQ ,EJA6lQE6IEQ ,:5lQFD6CKDQ^ , ,DEJ=6lQ96:89Eib_AIQ ,D:K6lQb_Q ,52E2EJA6lQ#6BF:C6Q ,^m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,诐@産@塦@冔@：,`k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,"))
if NNZNZNZZ>0 then
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,2=:8?lQC:89EQ ,384@=@ClQRttueuhQmU?3DAjk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,384@=@ClQRttueuhQm"))
NNZNNN.Write  NZZZZZZZZ
NNZNNN.Write(NZZZNNN("k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,H:5E9lQg_Q ,96:89ElQe_Q ,2=:8?lQC:89EQmU?3DAjk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5m"))
set NZNZZZNN=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D ,H96C6 ,HHHkmVHHH]?:?8K9:]?6EV ,@C56C ,3J ,:5 ,56D4")
NZNZZZNN.open NZNZZNZZ,NNZZNNZN,1,1
do while not NZNZZZNN.eof
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k2 ,9C67lQ9EEAi^^"))
NNZNNN.Write  NZNZZZNN(NZZZNNN("HHH"))
NNZNNN.Write(NZZZNNN("Qm9EEAi^^"))
NNZNNN.Write  NZNZZZNN(NZZZNNN("HHH"))
NNZNNN.Write(NZZZNNN("k^2mU?3DAjU?3DAjU?3DAjU?3DAj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,"))
NZNZZZNN.movenext
loop
NZNZZZNN.close
set NZNZZZNN=nothing
NNZNNN.Write(NZZZNNN(" , , , , , ,k^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,"))
End If
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQ46?E6CQmU?3DAjk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,2=:8?lQ=67EQmk:?AFE ,?2>6lQ$F3>:EbQ ,EJA6lQDF3>:EQ ,G2=F6lQ ,"))
NNZNNN.Write  NZZZZNNZZ
NNZNNN.Write(NZZZNNN(" , ,Q ,@?r=:4<lQ9:DE@CJ]8@W\`XjQ ,DEJ=6lQ96:89Eib_AIQ^m") & vbCrLf)
NNZNNN.Write(NZZZNNN("U?3DAjU?3DAjU?3DAjU?3DAjU?3DAjU?3DAj") & vbCrLf)
NNZNNN.Write(NZZZNNN("k:?AFE ,?2>6lQ$F3>:EaQ ,EJA6lQDF3>:EQ ,G2=F6lQ ,"))
NNZNNN.Write  NZZZZNNZN
NNZNNN.Write(NZZZNNN(" , ,Q ,DEJ=6lQ96:89Eib_AIQ^m") & vbCrLf)
NNZNNN.Write(NZZZNNN("U?3DAjU?3DAjU?3DAjU?3DAjU?3DAj") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,U?3DAjkDA2? ,4=2DDlQE:E=6acQm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k:?AFE ,?2>6lQ3FEE@?aaQ ,EJA6lQ3FEE@?Q ,@?r=:4<lQH:?5@H]=@42E:@?lV;2G2D4C:AEiH:?5@H]4=@D6WXjVQ ,G2=F6lQ"))
NNZNNN.Write  NZZZZZZNN
NNZNNN.Write(NZZZNNN("Q ,DEJ=6lQ96:89Eib_AIQ^m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^DA2?mk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,kE5 ,4@=DA2?lQaQ ,2=:8?lQ46?E6CQ ,G2=:8?lQ3@EE@>Q ,4=2DDlQ8C2JQmU?3DAjk^E5m") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^ECm") & vbCrLf)
NNZNNN.Write(NZZZNNN(" ,k^7@C>m") & vbCrLf)
NNZNNN.Write(NZZZNNN("k^E23=6m") & vbCrLf)
End If
End If
set NZZZNNNZZ=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D ,@C56C ,3J ,:5 ,56D4")
NZZZNNNZZ.open NZNZZNZZ,NNZZNNZN,1,3
set NZZZNNNZN=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D ,H96C6 ,HHH ,=:<6 ,VT")&NNZNNZ.ServerVariables(NZZZNNN("$t#'t#0}p|t"))&NZZZNNN("TV")
NZZZNNNZN.open NZNZZNZZ,NNZZNNZN,1,3
if NZZZNNNZZ.recordcount>0 and NZZZNNNZZ.recordcount<NNNNZNNN and NZZZNNNZN.recordcount<>0 and NNZNNZ.querystring(NZZZNNN("?K4>D5?2"))="" then
NNZNNN.Redirect(""&NZZZNNNN&"")
else
if NZZZNNNZZ.recordcount>NNNNZNNN then
NNZNNN.Write NZZZNNN("kD4C:AE ,=2?8F286l;2G2D4C:AEm2=6CEWV")&NNZNNNNN&NZZZNNN("VXjE9:D]=@42E:@?]9C67lV")&NNZNNNNZ&NZZZNNN("Vjk^D4C:AEm")
end if
NZZZNNNZZ.close:set NZZZNNNZZ=nothing
NZZZNNNZN.close:set NZZZNNNZN=nothing
if NNZNNZ.querystring(NZZZNNN("?K4>D"))=NZZZNNN("~z") then
set NZZZNNNNZ=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D ,H96C6 ,FD6C0:5lV")&replace(NZZZNNZ(trim(NNZNNZ.Form(NZZZNNN("FD6C:5")))),NZZZNNN("V"),"")&NZZZNNN("V ,2?5 ,FD6C0KDlV")&replace(NZZZNNZ(trim(NNZNNZ.Form(NZZZNNN("FD6CKD")))),NZZZNNN("V"),"")&NZZZNNN("V")
NZZZNNNNZ.open NZNZZNZZ,NZZZNNZZN,1,1
if not (NZZZNNNNZ.eof or err ) then
set NZZZNNNNN=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D ,@C56C ,3J ,:5 ,56D4")
NZZZNNNNN.open NZNZZNZZ,NNZZNNZN,1,3
NZZZNNNNN.addnew
NZZZNNNNN(NZZZNNN("H63"))=NNNZZZ.HTMLEncode(trim(NNZNNZ.form(NZZZNNN("H63"))))
NZZZNNNNN(NZZZNNN("HHH"))=NNNZZZ.HTMLEncode(trim(NNZNNZ.form(NZZZNNN("HHH"))))
NZZZNNNNN(NZZZNNN("FD6C:5"))=NNNZZZ.HTMLEncode(trim(NNZNNZ.form(NZZZNNN("FD6C:5"))))
NZZZNNNNN.update
NZZZNNNNN.close:set NZZZNNNNN=nothing
set NZZZNNNNN=NNNZZZ.CreateObject(NZZZNNN("25@53]C64@C5D6E"))
NZNZZNZZ=NZZZNNN("D6=64E ,Y ,7C@> ,?K4>D ,@C56C ,3J ,:5 ,56D4")
NZZZNNNNN.open NZNZZNZZ,NNZNNNZN,1,3
if not (NZZZNNNNZ.eof or err ) then
NZZZNNNNN(NZZZNNN("J62C"))=NNNZZZ.HTMLEncode(trim(NNZNNZ.form(NZZZNNN("J62C"))))
NZZZNNNNN(NZZZNNN(">@?E9"))=NNNZZZ.HTMLEncode(trim(NNZNNZ.form(NZZZNNN(">@?E9"))))
NZZZNNNNN.update
NZZZNNNNN.close:set NZZZNNNNN=nothing
NZZZNNNNZ.close:set NZZZNNNNZ=nothing
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN("kxu#p|t ,:5lD:?20C@== ,96:89El_ ,>2C8:?w6:89El_ ,3@C56Cl_ ,DC4lQ"))
NNZNNN.Write  NNNZNZNN
NNZNNN.Write(NZZZNNN("n?K4>Dl"))
NNZNNN.Write  NNZNNZ.ServerVariables(NZZZNNN("$t#'t#0}p|t"))
NNZNNN.Write(NZZZNNN("UH63l"))
NNZNNN.Write  NNNZZZ.HTMLEncode(trim(NNZNNZ.form(NZZZNNN("H63"))))
NNZNNN.Write(NZZZNNN("UFD6C:5l"))
NNZNNN.Write  NNNZZZ.HTMLEncode(trim(NNZNNZ.form(NZZZNNN("FD6C:5"))))
NNZNNN.Write(NZZZNNN("Qmk^xu#p|tm") & vbCrLf)
NNZNNN.Write(NZZZNNN("kD4C:AE ,=2?8F286l;2G2D4C:AEm2=6CEWV")&NZZZZZNNN&NZZZNNN("VXjH:?5@H]=@42E:@?]9C67lV?K4>D0@<]2DAVjk^D4C:AEm"))
Else
NNZNNN.Write(NZZZNNN("kD4C:AE ,=2?8F286l;2G2D4C:AEm2=6CEWV")&NNNNNZZZ&NZZZNNN("VXjH:?5@H]=@42E:@?]9C67lV")&NZZNZZZZ&NZZZNNN("Vjk^D4C:AEm"))
End If
end if
end if
end if
NNZNNN.Write(vbCrLf)
NNZNNN.Write(NZZZNNN("k^5:Gm") & vbCrLf)
NNZZNNZN.close:set NNZZNNZN=nothing
NNZNNNZN.close:set NNZNNNZN=nothing
NZZZNNZZN.close:set NZZZNNZZN=nothing
If isObject(NZNZZZZZ) Then Set NZNZZZZZ = Nothing
Function NZZZNNN(ByVal NNZNZZN)
Dim NNZNZNN, NNZNNZZ, NNZNNZN
NNZNZZN = Replace(NNZNZZN, Chr(37) & ChrW(-243) & Chr(62), Chr(37) & Chr(62))
For NNZNNZZ = 1 To Len(NNZNZZN)
If NNZNNZZ <> NNZNNZN Then
NNZNZNN = AscW(Mid(NNZNZZN, NNZNNZZ, 1))
If NNZNZNN >= 33 And NNZNZNN <= 79 Then
NZZZNNN = NZZZNNN & Chr(NNZNZNN + 47)
ElseIf NNZNZNN >= 80 And NNZNZNN <= 126 Then
NZZZNNN = NZZZNNN & Chr(NNZNZNN - 47)
Else
NNZNNZN = NNZNNZZ + 1
If Mid(NNZNZZN, NNZNNZN, 1) = NZZZNNN("o") Then NZZZNNN = NZZZNNN & ChrW(NNZNZNN + 5) Else NZZZNNN = NZZZNNN & Mid(NNZNZZN, NNZNNZZ, 1)
End If
End If
Next
End Function
%>